var app = angular.module('submitExample',['ngMaterial']);
var messages = j('.messages-content'), d, i = 0, msg = "", botmsg = "";

	function setDate() {
		d = new Date();
		j('<div class="timestamp">' + formatAMPM(d) + '</div>').appendTo(j('.message'));
	}

	function insertMessage(msg) {
		if (j.trim(msg) == '') {
			return false;
		}
		var correctEle = j('.messages-content').find('#mCSB_2_container');
		j('<div class="message message-personal">' + msg + '</div>').appendTo(correctEle).addClass('new');
		setDate();
		j('.message-input').val(null);
		updateScrollbar();
	}

	function updateScrollbar() {
		messages.mCustomScrollbar("update").mCustomScrollbar('scrollTo', 'bottom', {
			scrollInertia: 10,
			timeout: 0
		});
	}

	function formatAMPM(date) {
		var hours = date.getHours();
		var minutes = date.getMinutes();
		var ampm = hours >= 12 ? 'pm' : 'am';
		hours = hours % 12;
  		hours = hours ? hours : 12; // the hour '0' should be '12'
  		minutes = minutes < 10 ? '0'+minutes : minutes;
  		var strTime = hours + ':' + minutes + ' ' + ampm;
  		return strTime;
	}

	app.controller('ExampleController', ['$rootScope','$scope','$http','$compile', function($rootScope,$scope, $http, $compile) {
	var i;
	$scope.id = 0;
	$rootScope.default_input = true;
	$rootScope.car_model_input = false;

	$rootScope.GetConversationId = function ()
	{
		console.log($scope.name);
		if ($scope.name === undefined)
		{
			$http({
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Authorization': 'BotConnector Ue5czMiWVXY.cwA.gO0.NL0UQrpbuAOfoTOyYNN1bcbz9HHWf1GbzNpQ4dM9V78'
				},
				url: 'https://directline.botframework.com/api/conversations'
			})
			.then(function(response) {
				$scope.conversationId = response.data['conversationId'];
				var correctEle = j('.messages-content').find('#mCSB_2_container');
				j('<div class="message loading new"><figure class="avatar"><img src="icon.png" /></figure><span></span></div>').appendTo(correctEle);
				setTyping();
				j('.message-input').prop('disabled',false);
				updateScrollbar();
				setTimeout(function(){ 
					PostMessage();
				},1000);
			});
		}
		else
		{

			setTimeout(function(){
				var correctEle = j('.messages-content').find('#mCSB_2_container');
				j('<div class="message loading new"><figure class="avatar"><img src="icon.png" /></figure><span></span></div>').appendTo(correctEle);
				setTyping();
				j('.message-input').prop('disabled',false);
				updateScrollbar();
			},500);
			setTimeout(function(){ 
				PostMessage();
			},1000);
		}
	}

	function PostMessage()
	{
		if ($scope.name === undefined)
		{
			$http({
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Authorization': 'BotConnector Ue5czMiWVXY.cwA.gO0.NL0UQrpbuAOfoTOyYNN1bcbz9HHWf1GbzNpQ4dM9V78'
				},
				url: 'https://directline.botframework.com/api/conversations/'+$scope.conversationId+'/messages',
				data: {
					"conversationId":$scope.conversationId,
					"text": "Hi"
				}
			})
			.success(function(data, status){
				setTimeout(function(){ 
					GetMessage();
				}, 7000);
			});	  
		}
		else
		{
			$http({
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Authorization': 'BotConnector Ue5czMiWVXY.cwA.gO0.NL0UQrpbuAOfoTOyYNN1bcbz9HHWf1GbzNpQ4dM9V78'
				},
				url: 'https://directline.botframework.com/api/conversations/'+$scope.conversationId+'/messages',
				data: {
					"conversationId":$scope.conversationId,
					"text": ($scope.autocomplete_value === undefined) ? $scope.name : $scope.autocomplete_value,
					"from":$scope.fromBot
				}
			})
			.success(function(data, status){
				setTimeout(function(){ 
					GetMessage();
				}, 7000);
			});
			delete $rootScope.autocomplete_value;
	}
	}
	var lastTemp = 0;
			
	function GetMessage()
	{
		$http({
			method: 'GET',
			headers: {
				'Content-Type': 'application/json',
				'Authorization': 'BotConnector Ue5czMiWVXY.cwA.gO0.NL0UQrpbuAOfoTOyYNN1bcbz9HHWf1GbzNpQ4dM9V78'
			},
			url: 'https://directline.botframework.com/api/conversations/'+$scope.conversationId+'/messages',
		}).success(function(response){
			// getNextID(response["messages"], true);

			console.log(response["messages"]);
			for (var j = lastTemp + 1; j < (response["messages"].length); j++){
				botMessage(response["messages"][j],false);
			}
			lastTemp = response["messages"].length;
			if ($scope.fromBot === undefined) { $scope.fromBot = response["messages"][0]["from"]; } 
		});
	}
	
	$scope.submit = function() {	
		insertMessage(j('.message-input').val());
		if ($scope.name) {
			$rootScope.GetConversationId();
		}
	}
	
	j(window).load(function () {
		j('.md-virtual-repeat-scroller').mCustomScrollbar();
		messages.mCustomScrollbar();
		$rootScope.GetConversationId();
	});
	

	function setTyping() {
		j('<div class="timestamp">Typing...</div>').appendTo(j('.message:last'));
		j('.message-input').prop('disabled',true);
	}

	function botMessage(botmsg, imgOrNot) {
		// if (j('.message-input').val() != '') {
			// return false;
		// }
		j('.message.loading').remove();
		j('.message.timestamp').remove();
		var options = getArrayStringBotMsg(botmsg);
		var actualOptions = '<div class="message new"><figure class="avatar"><img src="icon.png" /></figure>';
		if(options.length <= 1){
			actualOptions += options[0];
		}
		else if(options.length > 1)
		{
			for (i = 0; i < options.length; i++) {
				actualOptions += '<button class="button" ng-click="optionClick(\''+ options[i].replace(/'/g, "\\'") +'\')" value="'+options[i]+'">'+options[i]+'</button>';
			}
		}
		else
		{
			actualOptions += options[0];
		}
		actualOptions += '</div>';
		if(options[0].match("^Which Car do you drive?")){
			$rootScope.default_input = false;
			$rootScope.car_model_input = true;
		}
		else
		{
			$rootScope.default_input = true;
			$rootScope.car_model_input = false;	
		}
		
		// j('#details').append("CarModel"+carModel+"carCost"+carCost+"carRegNo"+carRegNo+"DoP"+dop);
		$scope.test(actualOptions);
		playSound('bing');
		setDate();
		updateScrollbar(); 
	}
	
	function getArrayStringBotMsg(bmsg){
		check_bmsg = /\*/.test(bmsg["text"]);
		var bmessage = [];
		if (check_bmsg === false){
			bmessage[0] = bmsg["text"];
		}
		else{
			bmess = bmsg["text"].split("\n\n");
			bmessage = bmess.map(function(s){ return s.slice(2)});
			if(bmessage[0] == "confirm_yes"){
				bmessage[0] = "Yes";
			}
			if(bmessage[1] == "confirm_no"){
				bmessage[1] = "No";
			}
		}
		return bmessage;
	}
	
	$scope.test = function(actualOptions) {
		var el = actualOptions;
		var correctEle = j('.messages-content').find('#mCSB_2_container');
		var element = angular.element(correctEle);
		var generated = element.append(el);
		$compile(generated.contents())($scope);
	}

	$scope.optionClick = function(value){
		var choice_value = value.split(".")[0];
		$scope.name = choice_value;
		setTimeout(function(){ 
			$scope.submit();
		}, 10);
	}
	
	function playSound(filename) {
		document.getElementById("sound").innerHTML = '<audio autoplay="autoplay"><source src="' + filename + '.mp3" type="audio/mpeg" /><source src="' + filename + '.ogg" type="audio/ogg" /><embed hidden="true" autostart="true" loop="false" src="' + filename + '.mp3" /></audio>';
	}
}]);

app.controller('autoCompleteController', autoCompleteController);
function autoCompleteController ($rootScope, $scope,$timeout, $q, $log) {
	var self = this;
	self.car = loadCar();
	self.querySearch   = querySearch;
	self.selectedItemChange = selectedItemChange;
	self.searchTextChange   = searchTextChange;

	$scope.submit1 = function() {
		$rootScope.default_input = true;
		$rootScope.car_model_input = false;
		insertMessage(j('#input-0').val());
		if (j('#input-0').val()){
			$rootScope.autocomplete_value = j('#input-0').val();	
		}
		$rootScope.GetConversationId();	
	}

	function querySearch (query) {
		var start = Math.floor(Math.random() * (self.car.length - 100));
		var end = 10 + start;
		var results = query ? self.car.filter(createFilterFor(query)) : self.car.slice(1, 10), deferred;

		if (self.simulateQuery) {
			deferred = $q.defer();
			$timeout(function () { 
				deferred.resolve(results); 
			}, 
			Math.random() * 1000, false);
			return deferred.promise;
		} else {
			return results;
		}
	}
	function searchTextChange(text) {
	}
	function selectedItemChange(item) {
	}
	//build list of states as map of key-value pairs
	function loadCar() {
			var arrCarList = new Array(
				"Hyundai Creta 1.4 Base, DIESEL",
				"Hyundai Creta 1.4 S, DIESEL",
				"Hyundai Creta 1.6 S, PETROL",
				"Hyundai Creta 1.6 SX, DIESEL",
				"Hyundai Creta 1.6 SX Plus AT, DIESEL",
				"Hyundai Creta 1.6 SX Plus MT, PETROL",
				"Hyundai Elantra 1.6 Base, DIESEL",
				"Hyundai Elantra 1.6 S MT, DIESEL",
				"Hyundai Elantra 1.6 SX AT, DIESEL",
				"Hyundai Elantra 1.6 SX MT, DIESEL",
				"Hyundai Elantra 1.8 S, PETROL",
				"Hyundai Elantra 1.8 SX AT, PETROL",
				"Hyundai Elantra 1.8 SX MT, PETROL",
				"Hyundai Elite i20 Asta 1.2, PETROL",
				"Hyundai Elite i20 Asta 1.4 CRDI, DIESEL",
				"Hyundai Elite i20 Era 1.2, PETROL",
				"Hyundai Elite i20 Era 1.4 CRDI, DIESEL",
				"Hyundai Elite i20 Magna 1.2, PETROL",
				"Hyundai Elite i20 Magna 1.4 CRDI, DIESEL",
				"Hyundai Elite i20 Sportz 1.2, PETROL",
				"Hyundai Elite i20 Sportz 1.4, DIESEL",
				"Hyundai Eon 1.0 Kappa Magna +, PETROL",
				"Hyundai Eon D-Lite, PETROL",
				"Hyundai Eon D-Lite +, PETROL",
				"Hyundai Eon Era + (Petrol), PETROL",
				"Hyundai Eon Era + (LPG), LPG",
				"Hyundai Eon Era + (LPG), CNG",
				"Hyundai Eon Magna + (Petrol), PETROL",
				"Hyundai Eon Magna + (LPG), LPG",
				"Hyundai Eon Magna + (LPG), CNG",
				"Hyundai Eon Sportz, PETROL",
				"Hyundai Fluidic Verna 1.4 CRDi, DIESEL",
				"Hyundai Fluidic Verna 1.4 VTVT, PETROL",
				"Hyundai Fluidic Verna 1.6 CRDi S, DIESEL",
				"Hyundai Fluidic Verna 1.6 CRDi SX, DIESEL",
				"Hyundai Fluidic Verna 1.6 CRDi SX AT, DIESEL",
				"Hyundai Fluidic Verna 1.6 VTVT S, PETROL",
				"Hyundai Fluidic Verna 1.6 VTVT S, DIESEL",
				"Hyundai Fluidic Verna 1.6 VTVT S AT, PETROL",
				"Hyundai Fluidic Verna 1.6 VTVT SX, PETROL",
				"Hyundai Grand i10 Asta 1.1 CRDi, DIESEL",
				"Hyundai Grand i10 Asta 1.2 Kappa VTVT, PETROL",
				"Hyundai Grand i10 Asta AT 1.2 Kappa VTVT, PETROL",
				"Hyundai Grand i10 Era 1.1 CRDi, DIESEL",
				"Hyundai Grand i10 Era 1.2 Kappa VTVT, PETROL",
				"Hyundai Grand i10 Magna 1.0 Kappa VTVT, LPG",
				"Hyundai Grand i10 Magna 1.0 Kappa VTVT, LPG",
				"Hyundai Grand i10 Magna 1.1 CRDi, DIESEL",
				"Hyundai Grand i10 Magna 1.2 Kappa VTVT, PETROL",
				"Hyundai Grand i10 Sportz 1.1 CRDi, DIESEL",
				"Hyundai Grand i10 Sportz 1.2 Kappa VTVT, PETROL",
				"Hyundai i10 1.1L iRDE Magna Special Edition, PETROL",
				"Hyundai i10 Era 1.1 iRDE2, PETROL",
				"Hyundai i10 Sportz 1.1 iRDE2, PETROL",
				"Hyundai i10 Sportz 1.1 (LPG), LPG",
				"Hyundai i10 Sportz 1.1 (LPG), CNG",
				"Hyundai i20 Active 1.2, PETROL",
				"Hyundai i20 Active 1.2 S, PETROL",
				"Hyundai i20 Active 1.2 SX, PETROL",
				"Hyundai i20 Active 1.4, DIESEL",
				"Hyundai i20 Active 1.4 S, DIESEL",
				"Hyundai i20 Active 1.4 SX, DIESEL",
				"Hyundai Santa Fe 2 WD AT, DIESEL",
				"Hyundai Santa Fe 2 WD MT, DIESEL",
				"Hyundai Santa Fe 4 WD AT, DIESEL",
				"Hyundai Xcent Base 1.1 CRDi, DIESEL",
				"Hyundai Xcent Base 1.2, PETROL",
				"Hyundai Xcent S 1.1 CRDi, DIESEL",
				"Hyundai Xcent S 1.2, PETROL",
				"Hyundai Xcent SX 1.1 CRDi, DIESEL",
				"Hyundai Xcent SX 1.2, PETROL",
				"Hyundai Xcent SX AT 1.2, PETROL",
				"Hyundai Accent GTX - Tornado, PETROL",
				"Hyundai Accent GLE, PETROL",
				"Hyundai Accent GLE, PETROL",
				"Hyundai Accent CRDi, DIESEL",
				"Hyundai Accent GLS 1.6, PETROL",
				"Hyundai Accent GLS 1.6, PETROL",
				"Hyundai Accent Viva, PETROL",
				"Hyundai Accent Viva CRDi, DIESEL",
				"Hyundai Elantra GLS, PETROL",
				"Hyundai Elantra CRDi, DIESEL",
				"Hyundai Elantra GT, PETROL",
				"Hyundai Getz Prime 1.3 GVS, PETROL",
				"Hyundai Getz Prime 1.1 GLE, PETROL",
				"Hyundai Getz Prime 1.1 GVS, PETROL",
				"Hyundai Getz Prime 1.3 GLS, PETROL",
				"Hyundai Getz Prime 1.3 GLX, PETROL",
				"Hyundai Getz Prime 1.5 GVS CRDi, DIESEL",
				"Hyundai i10 Asta 1.2 AT with Sunroof, PETROL",
				"Hyundai i10 Asta 1.2 AT with Sunroof, PETROL",
				"Hyundai i10 D-Lite, PETROL",
				"Hyundai i10 Era, PETROL",
				"Hyundai i10 Magna, PETROL",
				"Hyundai i10 Magna 1.2, PETROL",
				"Hyundai i10 Magna 1.2 AT, PETROL",
				"Hyundai i10 Sportz 1.2, PETROL",
				"Hyundai i10 Sportz 1.2 AT, PETROL",
				"Hyundai i10 Asta 1.2, PETROL",
				"Hyundai i20 Asta 1.4 AT, PETROL",
				"Hyundai i20 Magna 1.2, PETROL",
				"Hyundai i20 Sportz 1.2, PETROL",
				"Hyundai i20 Asta 1.2, PETROL",
				"Hyundai i20 Magna 1.4 CRDI, DIESEL",
				"Hyundai i20 Sportz 1.4 (Diesel), DIESEL",
				"Hyundai i20 Asta 1.4 CRDI, PETROL",
				"Hyundai i20 Asta 1.4 CRDI, DIESEL",
				"Hyundai i20 Era 1.2, PETROL",
				"Hyundai i20 Era 1.4 CRDI, DIESEL",
				"Hyundai i20 Asta 1.2 with AVN, PETROL",
				"Hyundai Santro Xing XL AT eRLX, PETROL",
				"Hyundai Santro Xing XL eRLX, PETROL",
				"Hyundai Santro Xing XK eRLX, PETROL",
				"Hyundai Santro Xing XO eRLX, PETROL",
				"Hyundai Sonata GLS, PETROL",
				"Hyundai Sonata GOLD, PETROL",
				"Hyundai Sonata S 20, PETROL",
				"Hyundai Sonata 2.7 V6, PETROL",
				"Hyundai Sonata Embera 2.0 CRDi AT, DIESEL",
				"Hyundai Sonata Embera MT, PETROL",
				"Hyundai Sonata Embera AT, PETROL",
				"Hyundai Sonata Embera 2.0 CRDi, PETROL",
				"Hyundai Sonata Transform 2.0 CRDi A/T, DIESEL",
				"Hyundai Sonata Transform 2.4 VTVT, PETROL",
				"Hyundai Sonata Transform 2.0 CRDi M/T, DIESEL",
				"Hyundai Tucson CRDi, DIESEL",
				"Hyundai Verna CRDI VGT SX AT 1.5, DIESEL",
				"Hyundai Verna i, PETROL",
				"Hyundai Verna Xi, PETROL",
				"Hyundai Verna VTVT 1.6, PETROL",
				"Hyundai Verna XXi, PETROL",
				"Hyundai Verna VTVT SX 1.6, PETROL",
				"Hyundai Verna VGT CRDi, DIESEL",
				"Hyundai Verna CRDI VGT 1.5, DIESEL",
				"Hyundai Verna Transform 1.5 SX AT CRDi, DIESEL",
				"Hyundai Verna Transform 1.6 VTVT, PETROL",
				"Hyundai Verna Transform 1.6 SX VTVT, PETROL",
				"Hyundai Verna Transform 1.5 CRDi, DIESEL",
				"Hyundai Verna Transform 1.5 SX CRDi, DIESEL",
				"Hyundai Santro Xing GLS (CNG), LPG",
				"Hyundai Santro Xing GLS (CNG), CNG",
				"Hyundai Santro Xing GLS (CNG), PETROL/CNG",
				"Hyundai Santro Xing Non-AC, PETROL",
				"Hyundai Santro Xing GL (Petrol), PETROL",
				"Hyundai Santro Xing GL (LPG), LPG",
				"Hyundai Santro Xing GL (LPG), CNG",
				"Hyundai Santro Xing GL (LPG), PETROL/LPG",
				"Hyundai Santro Xing GL Plus (Petrol), PETROL",
				"Hyundai Santro Xing GL Plus (LPG), LPG",
				"Hyundai Santro Xing GL Plus (LPG), CNG",
				"Hyundai Santro Xing GL Plus (LPG), PETROL/LPG",
				"Hyundai Santro Xing GLS AT, PETROL",
				"Hyundai Santro Xing GLS (Petrol), PETROL",
				"Hyundai Santro Xing GLS (LPG), LPG",
				"Hyundai Santro Xing GLS (LPG), CNG",
				"Hyundai Santro Xing GLS (LPG), PETROL/LPG",
				"Hyundai Santro Xing GL (CNG), CNG",
				"Hyundai Santro Xing GL (CNG), PETROL/CNG",
				"Hyundai i20 Sportz 1.4 AT (Petrol), PETROL",
				"Hyundai Accent Executive (Petrol), PETROL",
				"Hyundai Accent Executive (LPG), LPG",
				"Hyundai Accent Executive (LPG), CNG",
				"Hyundai Accent Executive (LPG), PETROL/LPG",
				"Hyundai Accent, CNG",
				"Hyundai Verna Fluidic 1.4 VTVT GL, PETROL",
				"Hyundai Verna Fluidic 1.6 VTVT, PETROL",
				"Hyundai Verna Fluidic 1.6 VTVT EX, PETROL",
				"Hyundai Verna Fluidic 1.4 VTVT CX, PETROL",
				"Hyundai Verna Fluidic 1.4 CRDi GL, DIESEL",
				"Hyundai Verna Fluidic VTVT 1.6 EX AT, PETROL",
				"Hyundai Verna Fluidic 1.4 CRDi EX, DIESEL",
				"Hyundai Verna Fluidic 1.6 CRDi, DIESEL",
				"Hyundai Verna Fluidic 1.6 VTVT SX AT, PETROL",
				"Hyundai Verna Fluidic 1.4 CRDi CX, DIESEL",
				"Hyundai Verna Fluidic 1.6 CRDi EX, DIESEL",
				"Hyundai Verna Fluidic CRDi 1.6 EX AT, DIESEL",
				"Hyundai Sonata 2.4 GDi AT, PETROL",
				"Hyundai Sonata 2.4 GDi MT, PETROL",
				"Hyundai Santa Fe 4 WD MT, DIESEL",
				"Hyundai Creta Base 1.6 Petrol Dual Vtvt, PETROL",
				"Hyundai Creta S+ 1.4 CRDI, DIESEL",
				"Hyundai Getz GL, PETROL",
				"Hyundai Getz GLE, PETROL",
				"Hyundai Grand I10 Magna 1.0 Petrol, PETROL",
				"Hyundai Santro Base, PETROL",
				"Hyundai Santro GL, PETROL",
				"Hyundai Santro GLS, PETROL",
				"Hyundai Santro GS, PETROL",
				"Hyundai Santro L2, PETROL",
				"Hyundai Santro LE, PETROL",
				"Hyundai Santro LP, PETROL",
				"Hyundai Santro LS, PETROL",
				"Hyundai Santro S, PETROL",
				"Hyundai Santro XD, PETROL",
				"Hyundai Santro Xing eRLX AT, PETROL",
				"Hyundai Verna Base 1.4 CRDI, DIESEL",
				"Hyundai Verna Base 1.4 Petrol VTVT, PETROL",
				"Hyundai Verna S 1.6 Crdi VGT (O), DIESEL",
				"Chevrolet Beat PS (Petrol), PETROL",
				"Chevrolet Beat LS (Petrol), PETROL",
				"Chevrolet Beat LT (Petrol), PETROL",
				"Chevrolet Beat PS (Diesel), DIESEL",
				"Chevrolet Beat LS (Diesel), DIESEL",
				"Chevrolet Beat LT (Diesel), DIESEL",
				"Chevrolet Sail Hatchback 1.2 Base, PETROL",
				"Chevrolet Sail Hatchback 1.2 LS, PETROL",
				"Chevrolet Sail Hatchback 1.3 Base, DIESEL",
				"Chevrolet Sail Hatchback 1.2 LT, PETROL",
				"Chevrolet Sail Hatchback 1.3 LS, DIESEL",
				"Chevrolet Sail Hatchback 1.3 LT, DIESEL",
				"Chevrolet Sail 1.2 Base, PETROL",
				"Chevrolet Sail 1.2 LS, PETROL",
				"Chevrolet Sail 1.3 Base, DIESEL",
				"Chevrolet Sail 1.2 LT, PETROL",
				"Chevrolet Sail 1.3 LS, DIESEL",
				"Chevrolet Sail 1.3 LT, DIESEL",
				"Chevrolet Enjoy 1.4 LS, PETROL",
				"Chevrolet Enjoy 1.4 LT, PETROL",
				"Chevrolet Enjoy 1.3 LS, DIESEL",
				"Chevrolet Enjoy 1.4 LTZ, PETROL",
				"Chevrolet Enjoy 1.3 LT, DIESEL",
				"Chevrolet Enjoy 1.3 LTZ, DIESEL",
				"Chevrolet Tavera Neo 3 Max, DIESEL",
				"Chevrolet Tavera Neo 3 LS, DIESEL",
				"Chevrolet Tavera Neo 3 LT, DIESEL",
				"Chevrolet Cruze LT, DIESEL",
				"Chevrolet Cruze LTZ, DIESEL",
				"Chevrolet Cruze LTZ AT, DIESEL",
				"Chevrolet Captiva LT, DIESEL",
				"Chevrolet Captiva LTZ AWD 2.2, DIESEL",
				"Chevrolet Trailblazer LTZ AT, DIESEL",
				"Chevrolet Aveo 1.4 (Petrol), PETROL",
				"Chevrolet Aveo LS 1.4, PETROL",
				"Chevrolet Aveo LT 1.6, PETROL",
				"Chevrolet Aveo 1.4 (CNG), CNG",
				"Chevrolet Aveo LT 1.4, PETROL",
				"Chevrolet Aveo U-VA LT 1.2, PETROL",
				"Chevrolet Aveo U-VA 1.2, PETROL",
				"Chevrolet Aveo U-VA LS 1.2, PETROL",
				"Chevrolet Beat LS (LPG), LPG",
				"Chevrolet Beat LS (LPG), CNG",
				"Chevrolet Beat LS (LPG), PETROL/LPG",
				"Chevrolet Beat LT (LPG), LPG",
				"Chevrolet Beat LT (LPG), CNG",
				"Chevrolet Beat LT (LPG), PETROL/LPG",
				"Chevrolet Captiva LTZ AWD AT, DIESEL",
				"Chevrolet Captiva LTZ AWD Xtreme, DIESEL",
				"Chevrolet Forester AWD, PETROL",
				"Chevrolet Optra LT AT 1.8, PETROL",
				"Chevrolet Optra 1.6, PETROL",
				"Chevrolet Optra LS 1.6, PETROL",
				"Chevrolet Optra LS 1.8, PETROL",
				"Chevrolet Optra LS AT 1.8, PETROL",
				"Chevrolet Optra LT 1.8, PETROL",
				"Chevrolet Optra LT Royale 1.6, PETROL",
				"Chevrolet Optra Elite 1.6, PETROL",
				"Chevrolet Optra Platinum 1.6, PETROL",
				"Chevrolet Optra Magnum LT 2.0 TCDi, DIESEL",
				"Chevrolet Optra Magnum LS 1.6, PETROL",
				"Chevrolet Optra Magnum Max 1.6, PETROL",
				"Chevrolet Optra Magnum LT 1.6, PETROL",
				"Chevrolet Optra Magnum LS 2.0 TCDi, DIESEL",
				"Chevrolet Optra Magnum MAX 2.0 TCDi, DIESEL",
				"Chevrolet Optra SRV 1.6 Opt, PETROL",
				"Chevrolet Optra SRV 1.6, PETROL",
				"Chevrolet Spark E 1.0, PETROL",
				"Chevrolet Spark 1.0, PETROL",
				"Chevrolet Spark PS 1.0 (Petrol), PETROL",
				"Chevrolet Spark LS 1.0 (Petrol), PETROL",
				"Chevrolet Spark LS 1.0 Muzic, PETROL",
				"Chevrolet Spark PS 1.0 (LPG), LPG",
				"Chevrolet Spark PS 1.0 (LPG), CNG",
				"Chevrolet Spark LT 1.0 (Petrol), PETROL",
				"Chevrolet Spark LS 1.0 (LPG), LPG",
				"Chevrolet Spark LS 1.0 (LPG), CNG",
				"Chevrolet Spark LT 1.0 (LPG), LPG",
				"Chevrolet Spark LT 1.0 (LPG), CNG",
				"Chevrolet Sail U-VA 1.3 LT, DIESEL",
				"Chevrolet Sail U-VA 1.2 Base, PETROL",
				"Chevrolet Sail U-VA 1.2 LS, PETROL",
				"Chevrolet Sail U-VA 1.3 Base, DIESEL",
				"Chevrolet Sail U-VA 1.2 LT, PETROL",
				"Chevrolet Sail U-VA 1.3 LS, DIESEL",
				"Chevrolet Tavera Neo 3 10-Seater, DIESEL",
				"Chevrolet Tavera Neo 3 9-Seater, DIESEL",
				"Mahindra Bolero DI 4WD I, DIESEL",
				"Mahindra Bolero DI AC I, DIESEL",
				"Mahindra Bolero DI I, DIESEL",
				"Mahindra Bolero EX AC, DIESEL",
				"Mahindra Bolero EX, DIESEL",
				"Mahindra Bolero LX 4WD, DIESEL",
				"Mahindra Bolero LX 4WD, DIESEL",
				"Mahindra Bolero Plus AC I, DIESEL",
				"Mahindra Bolero Plus AC I, DIESEL",
				"Mahindra Bolero Plus AC, DIESEL",
				"Mahindra Bolero Plus I, DIESEL",
				"Mahindra Bolero Plus I, DIESEL",
				"Mahindra Bolero ZLX I, DIESEL",
				"Mahindra KUV100 K2 (Petrol), PETROL",
				"Mahindra KUV100 K2 (Diesel), DIESEL",
				"Mahindra KUV100 K2+ (Petrol), PETROL",
				"Mahindra KUV100 K2+ (Diesel), DIESEL",
				"Mahindra KUV100 K4 (Petrol), PETROL",
				"Mahindra KUV100 K4 (Diesel), DIESEL",
				"Mahindra KUV100 K4+ (Petrol), PETROL",
				"Mahindra KUV100 K4+ (Diesel), DIESEL",
				"Mahindra KUV100 K6 (Petrol), PETROL",
				"Mahindra KUV100 K6 (Diesel), DIESEL",
				"Mahindra KUV100 K6+ (Petrol), PETROL",
				"Mahindra KUV100 K6+ (Diesel), DIESEL",
				"Mahindra KUV100 K8 (Petrol), PETROL",
				"Mahindra KUV100 K8 (Diesel), DIESEL",
				"Mahindra Quanto C2, DIESEL",
				"Mahindra Quanto C4, DIESEL",
				"Mahindra Quanto C6, DIESEL",
				"Mahindra Quanto C8, DIESEL",
				"Mahindra Scorpio Getaway 2WD, DIESEL",
				"Mahindra Scorpio Getaway 2WD, DIESEL",
				"Mahindra Scorpio Getaway 4WD, DIESEL",
				"Mahindra Scorpio S10, DIESEL",
				"Mahindra Scorpio S10 4WD, DIESEL",
				"Mahindra Scorpio S10 4WD AT, DIESEL",
				"Mahindra Scorpio S10 4WD AT, DIESEL",
				"Mahindra Scorpio S2, DIESEL",
				"Mahindra Scorpio S4, DIESEL",
				"Mahindra Scorpio S4 Plus, DIESEL",
				"Mahindra Scorpio S4 Plus, DIESEL",
				"Mahindra Scorpio S6 Plus, DIESEL",
				"Mahindra Scorpio S8, DIESEL",
				"Mahindra Thar CRDe 4x4 AC, DIESEL",
				"Mahindra Thar DI 2WD, DIESEL",
				"Mahindra Thar DI 4WD, DIESEL",
				"Mahindra TUV300 T4, DIESEL",
				"Mahindra TUV300 T6, DIESEL",
				"Mahindra TUV300 T8, DIESEL",
				"Mahindra Verito 1.5 D2, DIESEL",
				"Mahindra Verito 1.5 D4, DIESEL",
				"Mahindra Verito 1.5 D6, DIESEL",
				"Mahindra Verito Vibe CS 1.5 D2, DIESEL",
				"Mahindra Verito Vibe CS 1.5 D4, DIESEL",
				"Mahindra Verito Vibe CS 1.5 D6, DIESEL",
				"Mahindra XUV500 W10, DIESEL",
				"Mahindra XUV500 W10 AT, DIESEL",
				"Mahindra XUV500 W10 AWD, DIESEL",
				"Mahindra XUV500 W10 AWD AT, DIESEL",
				"Mahindra XUV500 W4, DIESEL",
				"Mahindra XUV500 W6, DIESEL",
				"Mahindra XUV500 W8, DIESEL",
				"Mahindra XUV500 W8 AT, DIESEL",
				"Mahindra XUV500 W8 AWD, DIESEL",
				"Mahindra XUV500 W8 AWD, DIESEL",
				"Mahindra Xylo D2, DIESEL",
				"Mahindra Xylo D4, DIESEL",
				"Mahindra Xylo H4, DIESEL",
				"Mahindra Bolero SLX 4WD, DIESEL",
				"Mahindra Bolero XL 9 Seater, DIESEL",
				"Mahindra Bolero XL 7 Seater, DIESEL",
				"Mahindra Bolero XL 7 Seater, DIESEL",
				"Mahindra Bolero XL10 Seater, DIESEL",
				"Mahindra Bolero SLX 2WD, DIESEL",
				"Mahindra Bolero VLX CRDe, DIESEL",
				"Mahindra Bolero Diz, DIESEL",
				"Mahindra Bolero Plus AC PS, DIESEL",
				"Mahindra Bolero SLE, DIESEL",
				"Mahindra Scorpio SLX 2.6 Turbo 7 Seater, DIESEL",
				"Mahindra Scorpio VLS AT 2.2 mHawk, DIESEL",
				"Mahindra Scorpio 2.6 Turbo 7 Seater, DIESEL",
				"Mahindra Scorpio 2.6 Turbo 9 Seater, DIESEL",
				"Mahindra Scorpio 2.6 Turbo 9 Seater, DIESEL",
				"Mahindra Scorpio M2DI, DIESEL",
				"Mahindra Scorpio LX 2.6 Turbo, DIESEL",
				"Mahindra Scorpio DX 2.6 Turbo 8 Seater, DIESEL",
				"Mahindra Scorpio DX 2.6 Turbo 8 Seater, DIESEL",
				"Mahindra Scorpio DX 2.6 Turbo 7 Seater, DIESEL",
				"Mahindra Scorpio DX 2.6 Turbo 7 Seater, DIESEL",
				"Mahindra Scorpio VLS 2.2 mHawk, DIESEL",
				"Mahindra Verito 1.4 G2, PETROL",
				"Mahindra Verito 1.4 G4, PETROL",
				"Mahindra Xylo E2, DIESEL",
				"Mahindra Xylo E4, DIESEL",
				"Mahindra Xylo E6, DIESEL",
				"Mahindra Xylo E8, DIESEL",
				"Mahindra Xylo Celebration Edition, DIESEL",
				"Mahindra Xylo H8, DIESEL",
				"Mahindra Xylo E9, DIESEL",
				"Mahindra Scorpio VLX 2WD AT, DIESEL",
				"Mahindra Scorpio VLX 4WD, DIESEL",
				"Mahindra Scorpio Ex, DIESEL",
				"Mahindra Scorpio Ex, DIESEL",
				"Mahindra Scorpio SLE 2.6 CRDe, DIESEL",
				"Mahindra Scorpio LX, DIESEL",
				"Mahindra Scorpio LX, DIESEL",
				"Mahindra Scorpio SLE, DIESEL",
				"Mahindra Scorpio LX 4WD BS-IV, DIESEL",
				"Mahindra Scorpio VLX Special Edition, DIESEL",
				"Mahindra Scorpio VLX 4WD Airbag AT 8 Seater, DIESEL",
				"Mahindra Scorpio VLX 4WD Airbag AT 8 Seater, DIESEL",
				"Mahindra Scorpio VLX 2WD, DIESEL",
				"Mahindra Scorpio VLX 2WD, DIESEL",
				"Mahindra Scorpio VLX 2WD Airbag, DIESEL",
				"Mahindra Scorpio VLX 2WD Airbag, DIESEL",
				"Mahindra Scorpio VLX 2WD Airbag AT BS-IV, DIESEL",
				"Mahindra Scorpio VLX 4WD Airbag 7 Seater, DIESEL",
				"Mahindra Scorpio VLX 4WD AT, DIESEL",
				"Mahindra XUV500 Sportz Ltd, DIESEL",
				"Mahindra XUV500 Sportz Ltd, DIESEL",
				"Mahindra XUV500 Xclusive, DIESEL",
				"Mahindra Bolero LX, DIESEL",
				"Mahindra Invader DI, DIESEL",
				"Mahindra Jeep 2.5L, DIESEL",
				"Mahindra Jeep CJ 500 Di, DIESEL",
				"Mahindra Jeep Mm 540, DIESEL",
				"Mahindra Logan Dle, DIESEL",
				"Mahindra Logan Dls, DIESEL",
				"Mahindra Logan Dlx, DIESEL",
				"Mahindra Logan Edge Connect DLS, DIESEL",
				"Mahindra Logan Edge Connect DLX, DIESEL",
				"Mahindra Logan Edge Connect GLS ABS, PETROL",
				"Mahindra Logan Edge Connect GLX, PETROL",
				"Mahindra Logan Edge GLS, PETROL",
				"Mahindra Logan Edge GLSX, PETROL",
				"Mahindra Logan Edge GLX, PETROL",
				"Mahindra Logan GL, PETROL",
				"Mahindra Logan GLE, PETROL",
				"Mahindra Logan GLS, PETROL",
				"Mahindra Logan GLX 1.4 Petrol, PETROL",
				"Mahindra Logan GLX 1.6 Petrol, PETROL",
				"Mahindra Logan Play DLX, DIESEL",
				"Mahindra Logan Play GLX, PETROL",
				"Mahindra Logan Tourer DLX Diesel, DIESEL",
				"Mahindra Logan Tourer GLX Petrol, PETROL",
				"Mahindra Scorpio S6 7 Seater, DIESEL",
				"Mahindra Scorpio S6 8 Seater, DIESEL",
				"Mahindra Supro LX, DIESEL",
				"Mahindra Supro VX 5 Seater, DIESEL",
				"Mahindra Supro VX 8 Seater, DIESEL",
				"Mahindra Supro VX, DIESEL",
				"Mahindra Supro ZX, DIESEL",
				"Mahindra Xylo H9 7 Seater, DIESEL",
				"Mahindra Xylo H9 8 Seater, DIESEL",
				"Skoda Rapid 1.6 MPI Active, PETROL",
				"Skoda Rapid 1.5 TDI CR Active, DIESEL",
				"Skoda Rapid 1.6 MPI Ambition, PETROL",
				"Skoda Rapid 1.6 MPI Style Plus, PETROL",
				"Skoda Rapid 1.5 TDI CR Ambition, DIESEL",
				"Skoda Rapid 1.6 MPI Style AT, PETROL",
				"Skoda Rapid 1.5 TDI CR Style Plus, DIESEL",
				"Skoda Rapid 1.6 MPI Style Plus AT, PETROL",
				"Skoda Rapid 1.5 TDI CR Ambition AT, DIESEL",
				"Skoda Rapid 1.5 TDI CR Style Plus AT, DIESEL",
				"Skoda Octavia 1.4 TSI Ambition, PETROL",
				"Skoda Octavia 2.0 TDI CR Ambition, DIESEL",
				"Skoda Octavia 2.0 TDI CR AT Ambition, DIESEL",
				"Skoda Octavia 1.8 TSI AT Style Plus, PETROL",
				"Skoda Octavia 2.0 TDI CR AT Style Plus, DIESEL",
				"Skoda Yeti Style 4x2, DIESEL",
				"Skoda Yeti Style 4x4, DIESEL",
				"Skoda Superb Elegance TDI AT, DIESEL",
				"Skoda Fabia Elegance 1.4 PD TDI, DIESEL",
				"Skoda Fabia Active 1.2 MPI, PETROL",
				"Skoda Fabia Classic 1.2 MPI, PETROL",
				"Skoda Fabia Active 1.4 PD TDI, DIESEL",
				"Skoda Fabia Classic 1.4 PD TDI, DIESEL",
				"Skoda Fabia Ambiente 1.2 MPI, PETROL",
				"Skoda Fabia Elegance 1.2MPI, PETROL",
				"Skoda Fabia Elegance 1.2MPI, DIESEL",
				"Skoda Fabia Ambiente 1.4 PD TDI, DIESEL",
				"Skoda Fabia Scout Scout 1.2 TDI, PETROL",
				"Skoda Fabia Scout Scout 1.2 TDI, DIESEL",
				"Skoda Fabia Scout Scout 1.2 MPI, PETROL",
				"Skoda Laura L&K 1.9 PD AT, DIESEL",
				"Skoda Laura L&K 1.9 PD, DIESEL",
				"Skoda Octavia RS 1.8 Turbo, PETROL",
				"Skoda Octavia Elegance AT 1.9 TDI, DIESEL",
				"Skoda Octavia Elegance 2.0 MPI, PETROL",
				"Skoda Octavia Rider 2.0 MPI, PETROL",
				"Skoda Octavia 1.9 TDI, DIESEL",
				"Skoda Octavia Ambiente 1.8 Turbo, PETROL",
				"Skoda Octavia Rider 1.8 Turbo, PETROL",
				"Skoda Octavia Rider 1.9 TDI, DIESEL",
				"Skoda Octavia Ambiente 1.9 TDI, DIESEL",
				"Skoda Octavia Rider AT 1.9 TDI, DIESEL",
				"Skoda Octavia Elegance 1.9 TDI, DIESEL",
				"Skoda Octavia L&K, DIESEL",
				"Skoda Octavia Combi RS, PETROL",
				"Skoda Octavia Combi L&K, DIESEL",
				"Skoda Superb 2.5 TDI AT, DIESEL",
				"Skoda Superb 2.8 V6 AT, PETROL",
				"Skoda Fabia Elegance 1.2 TDI, DIESEL",
				"Skoda Fabia Elegance 1.2 TDI, DIESEL",
				"Skoda Fabia Ambition 1.2 MPI, PETROL",
				"Skoda Fabia Ambition Plus 1.2 MPI, PETROL",
				"Skoda Fabia Classic 1.2 TDI, DIESEL",
				"Skoda Fabia Classic 1.2 TDI, DIESEL",
				"Skoda Fabia Active 1.2 TDI, DIESEL",
				"Skoda Fabia Ambiente 1.2 TDI, DIESEL",
				"Skoda Fabia Ambiente 1.2 TDI, DIESEL",
				"Skoda Fabia Ambition 1.2 TDI, DIESEL",
				"Skoda Fabia Elegance 1.6 MPI, PETROL",
				"Skoda Fabia Ambition Plus 1.2 TDI CR, DIESEL",
				"Skoda Rapid Active 1.6 MPI MT, PETROL",
				"Skoda Rapid Ambition 1.6 MPI MT, PETROL",
				"Skoda Rapid Leisure 1.6 MPI MT, PETROL",
				"Skoda Rapid Active 1.6 TDI CR MT, DIESEL",
				"Skoda Rapid Ambition 1.6 TDI CR MT, DIESEL",
				"Skoda Rapid Ambition 1.6 MPI AT Plus, PETROL",
				"Skoda Rapid Prestige Ambition 1.6 TDI CR MT Plus, DIESEL",
				"Skoda Rapid Leisure 1.6 MPI AT, PETROL",
				"Skoda Rapid Leisure 1.6 TDI CR MT Plus, DIESEL",
				"Skoda Rapid Elegance 1.6 MPI AT, PETROL",
				"Skoda Rapid Elegance 1.6 TDI CR MT, DIESEL",
				"Skoda Rapid 1.6 MPI Elegance, PETROL",
				"Skoda Rapid 1.6 MPI Elegance Plus, PETROL",
				"Skoda Rapid 1.6 MPI Ambition Plus AT, PETROL",
				"Skoda Rapid 1.5 TDI CR Ambition Plus, DIESEL",
				"Skoda Rapid 1.5 TDI CR Elegance, DIESEL",
				"Skoda Rapid 1.6 MPI Elegance AT, PETROL",
				"Skoda Rapid 1.6 MPI Elegance Plus AT, PETROL",
				"Skoda Rapid 1.5 TDI CR Elegance Plus, DIESEL",
				"Skoda Rapid 1.5 TDI CR Ambition Plus AT, DIESEL",
				"Skoda Rapid 1.5 TDI CR Elegance AT, DIESEL",
				"Skoda Rapid 1.5 TDI CR Elegance Plus AT, DIESEL",
				"Skoda Laura Classic 1.8 TSI, PETROL",
				"Skoda Laura Active 1.8 TSI, PETROL",
				"Skoda Laura Ambiente 1.8 TSI, PETROL",
				"Skoda Laura Ambiente 1.9 TDI, DIESEL",
				"Skoda Laura Ambiente 2.0 TDI CR, DIESEL",
				"Skoda Laura Ambition 2.0 TDI CR, DIESEL",
				"Skoda Laura Ambition 1.8 TSI, PETROL",
				"Skoda Laura Elegance 1.9 TDI, DIESEL",
				"Skoda Laura Elegance 2.0 TDI CR, DIESEL",
				"Skoda Laura RS, PETROL",
				"Skoda Octavia Active 1.4 TSI, PETROL",
				"Skoda Octavia Active 2.0 TDI CR, DIESEL",
				"Skoda Octavia Elegance 1.8 TSI AT, PETROL",
				"Skoda Octavia Elegance 2.0 TDI AT, DIESEL",
				"Skoda Superb 3.6 FSI 4x4, PETROL",
				"Skoda Superb 2.0 TDI PD, DIESEL",
				"Skoda Superb Ambition 1.8 TSI, PETROL",
				"Skoda Superb Elegance 1.8 TSI, PETROL",
				"Skoda Superb Ambition 2.0 TDI CR AT, DIESEL",
				"Skoda Yeti Elegance 4 X 4, DIESEL",
				"Skoda Yeti Elegance 4 X 2, DIESEL",
				"Skoda Superb Elegance Petrol AT, PETROL",
				"Skoda Yeti Active 4X2, DIESEL",
				"Skoda Yeti Ambiente, DIESEL",
				"Skoda Yeti Ambition 4X2, DIESEL",
				"Skoda Yeti Ambition 4X4, DIESEL",
				"Nissan Micra Active XL, PETROL",
				"Nissan Micra Active XV, PETROL",
				"Nissan Micra XL (Petrol), PETROL",
				"Nissan Micra XE (Diesel), DIESEL",
				"Nissan Micra XL (Diesel), DIESEL",
				"Nissan Micra X Shift, PETROL",
				"Nissan Micra XL CVT, PETROL",
				"Nissan Micra XV CVT, PETROL",
				"Nissan Micra XV (Diesel), DIESEL",
				"Nissan Sunny XE, PETROL",
				"Nissan Sunny XL, PETROL",
				"Nissan Sunny XE D, DIESEL",
				"Nissan Sunny XL D, DIESEL",
				"Nissan Sunny XV D, DIESEL",
				"Nissan Evalia XE, DIESEL",
				"Nissan Evalia XL, DIESEL",
				"Nissan Evalia XV, DIESEL",
				"Nissan Evalia SV, DIESEL",
				"Nissan Terrano XL (Petrol), PETROL",
				"Nissan Terrano XE (Diesel), DIESEL",
				"Nissan Terrano XL (Diesel), DIESEL",
				"Nissan Micra XV (Petrol), PETROL",
				"Nissan Micra XE (Petrol), PETROL",
				"Nissan Sunny XV, PETROL",
				"Nissan X-Trail Elegance, DIESEL",
				"Nissan X-Trail Comfort, DIESEL",
				"Nissan X-Trail X-Pecial, DIESEL",
				"Nissan Teana UPPER, PETROL",
				"Nissan Teana 230JM, PETROL",
				"Nissan Teana MID, PETROL",
				"Nissan X-Trail LE, DIESEL",
				"Nissan X-Trail SLX, DIESEL",
				"Nissan 370Z Touring Coupe, PETROL",
				"Nissan Terrano Xv Diesel Thp, DIESEL",
				"Volvo V40 D3 Kinetic, DIESEL",
				"Volvo V40 D3 R-Design, DIESEL",
				"Volvo V40 Cross Country T4 Momentum, PETROL",
				"Volvo V40 Cross Country D3 Inscription, DIESEL",
				"Volvo S60 Kinetic, DIESEL",
				"Volvo S60 Momentum, DIESEL",
				"Volvo S60 Inscription, DIESEL",
				"Volvo S60 T6, PETROL",
				"Volvo S80 Momentum, DIESEL",
				"Volvo S80 Inscription, DIESEL",
				"Volvo XC60 Kinetic, DIESEL",
				"Volvo XC60 Momentum, DIESEL",
				"Volvo XC60 Inscription, DIESEL",
				"Volvo XC90 Momentum Luxury, DIESEL",
				"Volvo XC90 Inscription Luxury, DIESEL",
				"Volvo S60 Summum D5, DIESEL",
				"Volvo S60 Kinetic D3, DIESEL",
				"Volvo S60 Summum D3, DIESEL",
				"Volvo S60 Kinetic D4, DIESEL",
				"Volvo S60 Summum D4, DIESEL",
				"Volvo S60 Kinetic D5, DIESEL",
				"Volvo XC60 Kinetic D4, DIESEL",
				"Volvo XC60 Summum D4, DIESEL",
				"Volvo XC60 D5 AWD AT, DIESEL",
				"Volvo S80 Kinetic D4, DIESEL",
				"Volvo S80 3.2, PETROL",
				"Volvo S80 Summum D4, DIESEL",
				"Volvo S80 V8 AWD, PETROL",
				"Volvo S80 Summum D5, DIESEL",
				"Volvo XC90 D5 AWD, DIESEL",
				"Volvo XC90 3.2 AWD, PETROL",
				"Volvo XC90 V8 AWD, PETROL",
				"Volvo XC60 D5 Summum, DIESEL",
				"Land Rover Freelander 2 S, DIESEL",
				"Land Rover Freelander 2 SE, DIESEL",
				"Land Rover Freelander 2 Sterling Edition, DIESEL",
				"Land Rover Freelander 2 HSE, DIESEL",
				"Land Rover Discovery Sport S, DIESEL",
				"Land Rover Discovery Sport SE, DIESEL",
				"Land Rover Discovery Sport HSE, DIESEL",
				"Land Rover Range Rover Evoque Pure, DIESEL",
				"Land Rover Range Rover Evoque SE, DIESEL",
				"Land Rover Range Rover Evoque HSE, DIESEL",
				"Land Rover Range Rover Evoque HSE Dynamic, DIESEL",
				"Land Rover Discovery SE, DIESEL",
				"Land Rover Discovery HSE, DIESEL",
				"Land Rover Range Rover Sport SDV6 S, DIESEL",
				"Land Rover Range Rover Sport SDV6 SE, DIESEL",
				"Land Rover Range Rover Sport SDV6 HSE, DIESEL",
				"Land Rover Range Rover Sport V8 SC Autobiography, PETROL",
				"Land Rover Range Rover Sport V8 SC SVR, PETROL",
				"Land Rover Range Rover LWB 3.0 V6 Vogue, DIESEL",
				"Land Rover Range Rover LWB 4.4 SDV8 Vogue SE, DIESEL",
				"Land Rover Range Rover LWB 4.4 SDV8 Autobiography, DIESEL",
				"Land Rover Range Rover LWB 5.0 V8 Autobiography, PETROL",
				"Land Rover Discovery 3 TDV6 Automatic, DIESEL",
				"Land Rover Range Rover 5.0 Supercharged V8, PETROL",
				"Land Rover Range Rover 3.6 TDV8 Vogue SE, DIESEL",
				"Land Rover Range Rover Sport 3.6 TDV8, DIESEL",
				"Land Rover Range Rover Sport 5.0 V8, PETROL",
				"Land Rover Range Rover Sport 3.0 TDV6 HSE, DIESEL",
				"Land Rover Range Rover Evoque Pure SD4, DIESEL",
				"Land Rover Range Rover Evoque Dynamic SD4, DIESEL",
				"Land Rover Range Rover Evoque Prestige SD4, DIESEL",
				"Land Rover Range Rover Evoque Dynamic Si4 Coupe, PETROL",
				"Land Rover Discovery 4 3.0L TDV6 SE, DIESEL",
				"Land Rover Discovery 3.0L SDV6 Landmark, DIESEL",
				"Land Rover Discovery Sport HSE Luxury TD4 7 Seater, DIESEL",
				"Land Rover Freelander 2 Td4 S Buisness Edition, DIESEL",
				"Land Rover Sport Super Charged V8 Petrol, PETROL",
				"Land Rover Sport V8 3.6 Td Diesel, DIESEL",
				"Land Rover Vogue Autobiography 4.4 Sdv8, DIESEL",
				"Land Rover Vogue Autobiography 4.4L Sdv8, DIESEL",
				"Land Rover Vogue Autobiography 5.0 V8 S/C, PETROL",
				"Land Rover Vogue V8 5.0 Supercharged Petrol, PETROL",
				"Audi A3 35 TDI Attraction, DIESEL",
				"Audi A3 35 TDI Premium, DIESEL",
				"Audi A3 40 TFSI Premium Plus, PETROL",
				"Audi A3 35 TDI Premium Plus, DIESEL",
				"Audi A3 35 TDI Technology, DIESEL",
				"Audi Q3 30 TDI S, DIESEL",
				"Audi Q3 35 TDI Premium, DIESEL",
				"Audi A4 35 TFSI Premium, PETROL",
				"Audi A4 35 TDI Premium, DIESEL",
				"Audi A4 35 TDI Premium Sport, DIESEL",
				"Audi A4 35 TDI Technology Pack, DIESEL",
				"Audi A3 Cabriolet 40 TFSI, PETROL",
				"Audi A3 Cabriolet 40 TFSI, PETROL",
				"Audi A6 35 TFSI, PETROL",
				"Audi A6 35 TDI, DIESEL",
				"Audi A6 S6 4.0 TFSI, PETROL",
				"Audi Q5 30 TDI Premium, DIESEL",
				"Audi Q5 30 TDI Technology, DIESEL",
				"Audi TT 45 TFSI, PETROL",
				"Audi S5 Sportback 3.0 TFSI Quattro, PETROL",
				"Audi Q7 45 TDI Premium Plus, DIESEL",
				"Audi Q7 45 TDI Technology Pack, DIESEL",
				"Audi RS5 4.2 Coupe, PETROL",
				"Audi A8 L 50 TDI, DIESEL",
				"Audi A8 L 60 TDI, DIESEL",
				"Audi A8 L 60 TFSI, PETROL",
				"Audi A8 L W12, PETROL",
				"Audi RS6 Avant, PETROL",
				"Audi R8 4.2 V8 Coupe, PETROL",
				"Audi R8 5.2 V10 Coupe, PETROL",
				"Audi R8 5.2 V10 Spyder, PETROL",
				"Audi R8 5.2 V10 Plus, PETROL",
				"Audi A4 2.0 TDI Multitronic, DIESEL",
				"Audi A4 1.8 T Multitronic, PETROL",
				"Audi A4 3.0 TDI Quattro, DIESEL",
				"Audi A4 1.8 TFSI, PETROL",
				"Audi A4 2.0 TFSI, PETROL",
				"Audi A4 2.0 TFSI, PETROL",
				"Audi A4 3.2 FSI Quattro, PETROL",
				"Audi A6 3.0 TDI Quattro, DIESEL",
				"Audi A6 3.0 I Multitronic, PETROL",
				"Audi A6 3.0 I Multitronic, PETROL",
				"Audi A6 3.2 FSI Quattro, PETROL",
				"Audi A6 3.2 FSI Quattro, PETROL",
				"Audi A6 2.8 FSI, PETROL",
				"Audi A6 3.0 TFSI Quattro, PETROL",
				"Audi A6 2.7 TDI, DIESEL",
				"Audi A8 L 6.0 W12 Quattro, PETROL",
				"Audi Q5 3.0 TDI Quattro, DIESEL",
				"Audi Q5 2.0 TFSI Quattro, PETROL",
				"Audi Q5 2.0 TDI Quattro, DIESEL",
				"Audi Q7 3.6 FSI Quattro, PETROL",
				"Audi Q7 4.2 FSI Quattro, PETROL",
				"Audi R8 Coupe 4.2 FSI Quattro, PETROL",
				"Audi TT 3.2 Coupe Quattro, PETROL",
				"Audi Q3 2.0 TDI Quattro Dynamic, DIESEL",
				"Audi Q3 2.0 TDI S Edition, DIESEL",
				"Audi Q3 2.0 TDI Base Grade, DIESEL",
				"Audi Q3 2.0 TFSI Quattro, PETROL",
				"Audi Q3 2.0 TDI Quattro Premium, DIESEL",
				"Audi A6 3.0 TDI Quattro Technology Pack, DIESEL",
				"Audi A6 2.0 TDI Premium, DIESEL",
				"Audi A6 35 TDI Premium, DIESEL",
				"Audi A6 35 TFSI Premium, PETROL",
				"Audi A6 35 TFSI Premium, PETROL",
				"Audi A6 2.0 TFSi Premium, PETROL",
				"Audi A6 2.0 TFSi Technology Pack, PETROL",
				"Audi A6 35 TDI Technology, DIESEL",
				"Audi A6 2.0 TDI Technology Pack, DIESEL",
				"Audi TT 2.0 TFSI Quattro, PETROL",
				"Audi Q7 4.2 TDI Quattro, DIESEL",
				"Audi Q7 3.0 TFSI Quattro, PETROL",
				"Audi Q7 3.0 TDI Quattro Premium, DIESEL",
				"Audi Q7 3.0 TDI Quattro Technology Pack, DIESEL",
				"Audi A7 Sportback 3.0 TDI Quattro, DIESEL",
				"Audi RS7 Sportback 4.0 TFSI Quattro, PETROL",
				"Audi A8 L 3.0 TDI Quattro, DIESEL",
				"Audi A3 35 TDI, DIESEL",
				"Audi Q3 35 TDI Quattro, DIESEL",
				"Audi Q5 Technology Edition 45 TDI Quattro, DIESEL",
				"Audi Q7 35 TDI Premium, DIESEL",
				"Audi Q7 35 TDI Premium Plus, DIESEL",
				"Audi Q7 35 TDI Technology Edition, DIESEL",
				"Audi Rs7 4 Tfsi Quattro, PETROL",
				"BMW 1 Series 118d, DIESEL",
				"BMW 3 Series 320d, DIESEL",
				"BMW 3 Series M3 Sedan, PETROL",
				"BMW 3 Series GT 320d, DIESEL",
				"BMW 5 Series M5, PETROL",
				"BMW X5 M, PETROL",
				"BMW Z4 sDrive 35i, PETROL",
				"BMW 7 Series 730Ld, DIESEL",
				"BMW 7 Series Active Hybrid, PETROL",
				"BMW 7 Series 750Li, PETROL",
				"BMW 7 Series 760Li, PETROL",
				"BMW 6 Series M6 Gran Coupe, PETROL",
				"BMW X6 M Coupe, PETROL",
				"BMW 4 Series M4 Coupe, PETROL",
				"BMW i8 1.5, PETROL",
				"BMW 3 Series 325i Sedan, PETROL",
				"BMW 3 Series 320d Highline Sedan, DIESEL",
				"BMW 3 Series 330i, PETROL",
				"BMW 3 Series 320i, PETROL",
				"BMW 5 Series 530i, PETROL",
				"BMW 5 Series 520d, DIESEL",
				"BMW 5 Series 520i, PETROL",
				"BMW 5 Series 525i, PETROL",
				"BMW 5 Series 525d, DIESEL",
				"BMW 5 Series 530d, DIESEL",
				"BMW 5 Series 523i, PETROL",
				"BMW 5 Series GT 530d, DIESEL",
				"BMW 6 Series Convertible, PETROL",
				"BMW 6 Series 650i, PETROL",
				"BMW 6 Series Coupe, PETROL",
				"BMW 6 Series 640d, DIESEL",
				"BMW 7 Series 740Li, PETROL",
				"BMW X1 sDrive20d, DIESEL",
				"BMW X1 sDrive18i, PETROL",
				"BMW X3 2.5si, PETROL",
				"BMW X3 xDrive20d, DIESEL",
				"BMW X5 4.8i, PETROL",
				"BMW X5 3.0d, DIESEL",
				"BMW X6 xDrive 30d, DIESEL",
				"BMW X3 xDrive30d, DIESEL",
				"BMW X6 xDrive 40d, DIESEL",
				"BMW X6 xDrive 50i, PETROL",
				"BMW M3, PETROL",
				"BMW X5 xDrive 50i, PETROL",
				"BMW M5, PETROL",
				"BMW 1 Series 116I, PETROL",
				"BMW 1 Series 118D Sport Line, DIESEL",
				"BMW 3 Series 320D Luxury Line, DIESEL",
				"BMW 3 Series 320D Prestige, DIESEL",
				"BMW 3 Series 320D Sport Line, DIESEL",
				"BMW 3 Series 320D Gran Turismo Luxury Line, DIESEL",
				"BMW 3 Series 320D Gran Turismo Sport Line, DIESEL",
				"BMW 3 Series 328I Sport Line, PETROL",
				"BMW 3 Series 330D Convertible, DIESEL",
				"BMW 5 Series 535I Automatic, PETROL",
				"BMW 5 Series 535I Manual, PETROL",
				"BMW 730Li Sedan, PETROL",
				"Honda Amaze 1.2 E i-VTEC, PETROL",
				"Honda Amaze 1.2 E i-VTEC, DIESEL",
				"Honda Amaze 1.2 EX i-VTEC, PETROL",
				"Honda Amaze 1.2 S AT i-VTEC, PETROL",
				"Honda Amaze 1.2 S i-VTEC, PETROL",
				"Honda Amaze 1.2 S Plus i-VTEC, PETROL",
				"Honda Amaze 1.2 S Plus i-VTEC, CNG",
				"Honda Amaze 1.2 SX i-VTEC, PETROL",
				"Honda Amaze 1.2 VX i-VTEC, PETROL",
				"Honda Amaze 1.2 VX AT i-VTEC, PETROL",
				"Honda Amaze 1.5 E i-DTEC, DIESEL",
				"Honda Amaze 1.5 EX i-DTEC, DIESEL",
				"Honda Amaze 1.5 S i-DTEC, DIESEL",
				"Honda Amaze 1.5 SX i-DTEC, DIESEL",
				"Honda Amaze 1.5 SX i-DTEC, DIESEL",
				"Honda Amaze 1.5 VX i-DTEC, DIESEL",
				"Honda Brio E MT, PETROL",
				"Honda Brio EX MT, PETROL",
				"Honda Brio S MT, PETROL",
				"Honda Brio V MT, PETROL",
				"Honda Brio VX AT, PETROL",
				"Honda Brio VX MT, PETROL",
				"Honda City E (Petrol), PETROL",
				"Honda City E (Diesel), DIESEL",
				"Honda City S (Petrol), PETROL",
				"Honda City S (Diesel), DIESEL",
				"Honda City SV (Petrol), PETROL",
				"Honda City SV AT (Petrol), PETROL",
				"Honda City SV (Diesel), DIESEL",
				"Honda City SV (Diesel), DIESEL",
				"Honda City SV (Diesel), DIESEL",
				"Honda City V (Petrol), PETROL",
				"Honda City V (Diesel), DIESEL",
				"Honda City VX (Petrol), PETROL",
				"Honda City VX MT (Petrol), PETROL",
				"Honda City VX MT (Diesel), DIESEL",
				"Honda City VX AT (Petrol), PETROL",
				"Honda City VX (Diesel), DIESEL",
				"Honda CR-V 2.0L 2WD AT, PETROL",
				"Honda CR-V 2.0L 2WD MT, PETROL",
				"Honda CR-V 2.4L 4WD AVN, PETROL",
				"Honda Jazz E iDTEC, DIESEL",
				"Honda Jazz E MT, PETROL",
				"Honda Jazz S AT, PETROL",
				"Honda Jazz S iDTEC, DIESEL",
				"Honda Jazz S MT, PETROL",
				"Honda Jazz SV iDTEC, DIESEL",
				"Honda Jazz SV MT, PETROL",
				"Honda Jazz V AT, PETROL",
				"Honda Jazz V iDTEC, DIESEL",
				"Honda Jazz V MT, PETROL",
				"Honda Jazz VX iDTEC, DIESEL",
				"Honda Jazz VX MT, PETROL",
				"Honda Mobilio E i-DTEC, DIESEL",
				"Honda Mobilio E i-VTEC, PETROL",
				"Honda Mobilio RS i-DTEC, DIESEL",
				"Honda Mobilio S i-DTEC, DIESEL",
				"Honda Mobilio S i-VTEC, PETROL",
				"Honda Mobilio V i-DTEC, DIESEL",
				"Honda Mobilio V i-VTEC, PETROL",
				"Honda Accord 3.0 V6 AT, PETROL",
				"Honda Accord 3.0 V6 AT, PETROL",
				"Honda Accord 2.4 VTi-L MT, PETROL",
				"Honda Accord 2.4 VTi-L AT, PETROL",
				"Honda Accord 2.4 MT, PETROL",
				"Honda Accord 2.4 Elegance MT, PETROL",
				"Honda Accord 2.4 AT, PETROL",
				"Honda Accord 2.4 Inspire MT, PETROL",
				"Honda Accord 2.4 Elegance AT, PETROL",
				"Honda Accord 2.4 Inspire AT, PETROL",
				"Honda Accord 3.5 V6, PETROL",
				"Honda Accord 3.5 V6 Inspire, PETROL",
				"Honda Brio V AT, PETROL",
				"Honda Brio SMT, PETROL",
				"Honda Brio SAT, PETROL",
				"Honda City 1.5 EXi New, PETROL",
				"Honda City 1.5 V AT Exclusive, PETROL",
				"Honda City 1.5 S MT, PETROL",
				"Honda City 1.5 E MT, PETROL",
				"Honda City 1.5 V MT, PETROL",
				"Honda City 1.5 S AT, PETROL",
				"Honda City 1.5 V MT Exclusive, PETROL",
				"Honda City 1.5 V AT, PETROL",
				"Honda City ZX VTEC Plus, PETROL",
				"Honda City ZX EXi, PETROL",
				"Honda City ZX GXi, PETROL",
				"Honda City ZX CVT, PETROL",
				"Honda City ZX VTEC, PETROL",
				"Honda Civic 1.8V AT, PETROL",
				"Honda Civic 1.8E MT, PETROL",
				"Honda Civic 1.8S AT, PETROL",
				"Honda Civic Sport, PETROL",
				"Honda Civic 1.8S MT, PETROL",
				"Honda Civic Hybrid, PETROL",
				"Honda Civic 1.8V MT, PETROL",
				"Honda CR-V 2.4 MT, PETROL",
				"Honda CR-V 2.4 AT, PETROL",
				"Honda Jazz Base, PETROL",
				"Honda Jazz Select Edition, PETROL",
				"Honda Jazz Mode, PETROL",
				"Honda Jazz X, PETROL",
				"Honda Jazz Active, PETROL",
				"Honda Jazz S, PETROL",
				"Honda Jazz Select, PETROL",
				"Honda City 1.5 Corporate MT, PETROL",
				"Honda City V MT Compatible, CNG",
				"Honda City V MT Compatible, PETROL/CNG",
				"Honda City V MT AVN, PETROL",
				"Honda City V AT AVN, PETROL",
				"Honda Amaze V, PETROL",
				"Mercedes-Benz A-Class A 180, PETROL",
				"Mercedes-Benz A-Class A 200d, DIESEL",
				"Mercedes-Benz B-Class B 200 CDI, DIESEL",
				"Mercedes-Benz CLA-Class 200 CDI, DIESEL",
				"Mercedes-Benz CLA-Class 200 Sport, PETROL",
				"Mercedes-Benz CLA-Class 45 AMG, PETROL",
				"Mercedes-Benz GLA-Class 200 CDI, DIESEL",
				"Mercedes-Benz GLA-Class 200 Sport, PETROL",
				"Mercedes-Benz GLA-Class 45 AMG 4MATIC, PETROL",
				"Mercedes-Benz E-Class E 250 CDI Avantgarde, DIESEL",
				"Mercedes-Benz E-Class E 350 CDI Avantgarde, DIESEL",
				"Mercedes-Benz E-Class E 63 AMG, PETROL",
				"Mercedes-Benz GLE-Class 250 d, DIESEL",
				"Mercedes-Benz GLE-Class 350 d, DIESEL",
				"Mercedes-Benz SLK-Class SLK 350, PETROL",
				"Mercedes-Benz SLK-Class SLK 55 AMG, PETROL",
				"Mercedes-Benz CLS-Class 250 CDI, DIESEL",
				"Mercedes-Benz CLS-Class 350, PETROL",
				"Mercedes-Benz GL-Class 350 CDI, DIESEL",
				"Mercedes-Benz GL-Class 63 AMG, PETROL",
				"Mercedes-Benz E-Class Cabriolet E 400 Cabriolet, PETROL",
				"Mercedes-Benz GLE Coupe 450 AMG, PETROL",
				"Mercedes-Benz S-Class S 350 CDI, DIESEL",
				"Mercedes-Benz S-Class S 500, PETROL",
				"Mercedes-Benz S-Class Maybach S 500, PETROL",
				"Mercedes-Benz S-Class S 63 AMG, PETROL",
				"Mercedes-Benz S-Class Maybach S 600, PETROL",
				"Mercedes-Benz S-Class S Guard, PETROL",
				"Mercedes-Benz M-Class ML 63 AMG, PETROL",
				"Mercedes-Benz M-Class M Guard, PETROL",
				"Mercedes-Benz S-Coupe S 500 4MATIC, PETROL",
				"Mercedes-Benz S-Coupe S 63 AMG, PETROL",
				"Mercedes-Benz AMG GT S, PETROL",
				"Mercedes-Benz C-Class 200 CDI Elegance, DIESEL",
				"Mercedes-Benz C-Class 180 Elegance MT, PETROL",
				"Mercedes-Benz C-Class 180 Classic, PETROL",
				"Mercedes-Benz C-Class 200 CDI Classic, DIESEL",
				"Mercedes-Benz C-Class 220 CDI AT, DIESEL",
				"Mercedes-Benz C-Class 200 K MT, PETROL",
				"Mercedes-Benz C-Class 220 CDI MT, DIESEL",
				"Mercedes-Benz C-Class 200 K AT, PETROL",
				"Mercedes-Benz C-Class 63 AMG, PETROL",
				"Mercedes-Benz C-Class 230 Avantgarde, PETROL",
				"Mercedes-Benz C-Class 200 K Elegance AT, PETROL",
				"Mercedes-Benz C-Class 250 CDI Avantgarde, DIESEL",
				"Mercedes-Benz C-Class 250 Avantgarde, PETROL",
				"Mercedes-Benz C-Class 250 CDI Classic, DIESEL",
				"Mercedes-Benz C-Class 250 CDI Elegance, DIESEL",
				"Mercedes-Benz CLS 63 AMG, PETROL",
				"Mercedes-Benz CLS 500, PETROL",
				"Mercedes-Benz E-Class 240 V6 MT, PETROL",
				"Mercedes-Benz E-Class 270 CDI, DIESEL",
				"Mercedes-Benz E-Class 240 V6 AT, PETROL",
				"Mercedes-Benz E-Class 220 CDI Sport, DIESEL",
				"Mercedes-Benz E-Class 200 K Classic, PETROL",
				"Mercedes-Benz E-Class 280 CDI Elegance, DIESEL",
				"Mercedes-Benz E-Class 280 Elegance, PETROL",
				"Mercedes-Benz E-Class E250 CDI Classic, DIESEL",
				"Mercedes-Benz E-Class E250 Elegance, PETROL",
				"Mercedes-Benz E-Class E220 CDI Blue Efficiency, DIESEL",
				"Mercedes-Benz E-Class E250 CDI BlueEfficiency, DIESEL",
				"Mercedes-Benz E-Class E350, PETROL",
				"Mercedes-Benz E-Class E350 CDI BlueEfficiency, DIESEL",
				"Mercedes-Benz E-Class E350 CDI Avantgarde, DIESEL",
				"Mercedes-Benz GL 500, PETROL",
				"Mercedes-Benz GL 3.0 Grand Edition Executive, DIESEL",
				"Mercedes-Benz GL 3.0 Grand Edition Luxury, DIESEL",
				"Mercedes-Benz M-Class 350 CDI, DIESEL",
				"Mercedes-Benz M-Class 350, PETROL",
				"Mercedes-Benz S-Class 350, PETROL",
				"Mercedes-Benz SLK-Class SLK 200 K, PETROL",
				"Mercedes-Benz A-Class A 200 CDI, DIESEL",
				"Mercedes-Benz A-Class A 180 CDI Style, DIESEL",
				"Mercedes-Benz A-Class A 180 Sport Petro, PETROL",
				"Mercedes-Benz A-Class Edition 1, DIESEL",
				"Mercedes-Benz B-Class B180, PETROL",
				"Mercedes-Benz B-Class B180 CDI, DIESEL",
				"Mercedes-Benz B-Class Edition 1, DIESEL",
				"Mercedes-Benz C-Class 200 CGI, PETROL",
				"Mercedes-Benz C-Class 250 CDI, DIESEL",
				"Mercedes-Benz C-Class Grand Edition, PETROL",
				"Mercedes-Benz C-Class 220 BlueEfficiency, DIESEL",
				"Mercedes-Benz C-Class Edition C, DIESEL",
				"Mercedes-Benz C-Class Grand Edition CDI, DIESEL",
				"Mercedes-Benz R-Class R350 4MATIC, PETROL",
				"Mercedes-Benz R-Class R350 CDI 4Matic, DIESEL",
				"Mercedes-Benz CLS 350 BlueEFFICIENCY, PETROL",
				"Mercedes-Benz SL 350, PETROL",
				"Mercedes-Benz E-Class E200, PETROL",
				"Mercedes-Benz E-Class E250 CDI Launch Edition, DIESEL",
				"Mercedes-Benz SLS AMG Coupe, PETROL",
				"Mercedes-Benz C 200 Cgi Avantgarde, PETROL",
				"Mercedes-Benz C 220 D, DIESEL",
				"Mercedes-Benz E-Class 200 Cgi Blueefficiency, PETROL",
				"Mercedes-Benz G 63 AMG, PETROL",
				"Mercedes-Benz G 65 AMG, PETROL",
				"Mercedes-Benz Ml 250 CDI, DIESEL",
				"Mercedes-Benz Ml 320 CDI, DIESEL",
				"Mercedes-Benz S 300L, PETROL",
				"Mercedes-Benz S 320L CDI, DIESEL",
				"Mercedes-Benz Slk 250 Blueefficiency, PETROL",
				"Mercedes-Benz Viano 2.2 CDI, DIESEL",
				"Mercedes-Benz Viano 2.2 CDI Touchshift, DIESEL",
				"Mercedes-Benz Viano 3.0 V6 Touchshift, DIESEL",
				"Mercedes-Benz Viano 3.5 V6 Touchshift, DIESEL",
				"Bentley Continental Flying Spur V8, PETROL",
				"Bentley Continental Flying Spur W12, PETROL",
				"Bentley Continental GT V8, PETROL",
				"Bentley Continental GT V8S, PETROL",
				"Bentley Continental GT Coupe, PETROL",
				"Bentley Continental GT Speed, PETROL",
				"Bentley Continental GTC V8, PETROL",
				"Bentley Continental GTC Convertible, PETROL",
				"Bentley Continental GTC V8S, PETROL",
				"Bentley Continental GTC Speed, PETROL",
				"Bentley Mulsanne V8, PETROL",
				"Bentley Arnage R, PETROL",
				"Bentley Arnage RL, PETROL",
				"Bentley Azure Convertible, PETROL",
				"Bentley Brooklands, PETROL",
				"Bentley Mulsanne Speed, PETROL",
				"Porsche Cayman S Tiptronic, PETROL",
				"Porsche Cayman GTS, PETROL",
				"Porsche Macan S (Diesel), DIESEL",
				"Porsche Macan Turbo, PETROL",
				"Porsche Boxster S Tiptronic, PETROL",
				"Porsche Boxster GTS, PETROL",
				"Porsche Cayenne, DIESEL",
				"Porsche Cayenne S (Petrol), PETROL",
				"Porsche Cayenne S (Diesel), DIESEL",
				"Porsche Cayenne Turbo, PETROL",
				"Porsche Panamera, DIESEL",
				"Porsche Panamera Base, PETROL",
				"Porsche Panamera 4, DIESEL",
				"Porsche Panamera S E – Hybrid, PETROL",
				"Porsche Panamera GTS, DIESEL",
				"Porsche 911 Carrera, PETROL",
				"Porsche 911 Carrera 4, PETROL",
				"Porsche 911 Carrera Cabriolet, PETROL",
				"Porsche 911 Carrera S, PETROL",
				"Porsche 911 Targa 4, PETROL",
				"Porsche 911 Carrera 4 Cabriolet, PETROL",
				"Porsche 911 Carrera 4S, PETROL",
				"Porsche 911 Carrera S Cabriolet, PETROL",
				"Porsche 911 Targa 4S, PETROL",
				"Porsche 911 Carrera 4S Cabriolet, PETROL",
				"Porsche 911 GT3, PETROL",
				"Porsche 911 Turbo, PETROL",
				"Porsche 911 Turbo S, PETROL",
				"Porsche Cayenne Base, PETROL",
				"Porsche Cayenne S Hybrid, PETROL",
				"Porsche Cayenne GTS, PETROL",
				"Porsche Cayman AT, PETROL",
				"Porsche Cayman MT, PETROL",
				"Porsche Macan S (Petrol), PETROL",
				"Porsche Panamera Edition, PETROL",
				"Porsche Panamera Turbo, PETROL",
				"Porsche Panamera Turbo S, PETROL",
				"Ferrari California T, PETROL",
				"Ferrari FF 6.3L V12, PETROL",
				"Ferrari 488 GTB, PETROL",
				"Ferrari 488 Spider, PETROL",
				"Ferrari 458 Speciale, PETROL",
				"Ferrari F12berlinetta V12, PETROL",
				"Ferrari 599 GTB Fiorano Coupe, PETROL",
				"Ferrari 458 Italia Coupe, PETROL",
				"Ferrari F12 TDF, PETROL",
				"Jaguar XF 2.2, DIESEL",
				"Jaguar XF 2.0, PETROL",
				"Jaguar XF Aero-sport, DIESEL",
				"Jaguar XF S V6, DIESEL",
				"Jaguar XF R V8, PETROL",
				"Jaguar XJ L 3.0 V6 premium-luxury, DIESEL",
				"Jaguar XJ L 2.0 L Portfolio, PETROL",
				"Jaguar XJ L 3.0 V6 Portfolio, DIESEL",
				"Jaguar XJ L 3.0 V6, PETROL",
				"Jaguar XJ L 5.0 V8, PETROL",
				"Jaguar F-Type Coupe, PETROL",
				"Jaguar F-Type S Coupe, PETROL",
				"Jaguar F-Type V6 S Convertible, PETROL",
				"Jaguar F-Type V8 S Convertible, PETROL",
				"Jaguar F-Type R Coupe, PETROL",
				"Jaguar XF V8, PETROL",
				"Jaguar XK V8 Convertible Spl, PETROL",
				"Jaguar XK RS, PETROL",
				"Jaguar XK R V8 Coupe, PETROL",
				"Jaguar XK R V8 Convertible, PETROL",
				"Jaguar XK V8 Coupe Spl, PETROL",
				"Jaguar XJ L 2.0, PETROL",
				"Jaguar XJ L 3.0, DIESEL",
				"Lamborghini Huracan LP 580-2, PETROL",
				"Lamborghini Huracan LP 610-4, PETROL",
				"Lamborghini Aventador LP 700-4, PETROL",
				"Lamborghini Murcielago LP640, PETROL",
				"Lamborghini Gallardo LP 560-4, PETROL",
				"Lamborghini Gallardo Spyder, PETROL",
				"Lamborghini Gallardo India Ltd Edition LP 550-2, PETROL",
				"Bugatti Veyron 16.4 Grand Sport, PETROL",
				"Maruti Suzuki 800 AC, PETROL",
				"Maruti Suzuki 800 AC, PETROL",
				"Maruti Suzuki 800 AC Uniq, PETROL",
				"Maruti Suzuki 800 AC Uniq, PETROL",
				"Maruti Suzuki 800 Duo AC, LPG",
				"Maruti Suzuki 800 Duo AC, LPG",
				"Maruti Suzuki 800 Duo Std, LPG",
				"Maruti Suzuki 800 Duo Std, LPG",
				"Maruti Suzuki 800 Std, PETROL",
				"Maruti Suzuki 800 Std, PETROL",
				"Maruti Suzuki Alto 800 Lx (Petrol), PETROL",
				"Maruti Suzuki Alto 800 Lx (CNG), CNG",
				"Maruti Suzuki Alto 800 Lx (CNG), PETROL/CNG",
				"Maruti Suzuki Alto 800 Lxi (Petrol), PETROL",
				"Maruti Suzuki Alto 800 Lxi (CNG), CNG",
				"Maruti Suzuki Alto 800 Std (Petrol), PETROL",
				"Maruti Suzuki Alto 800 Std (CNG), LPG",
				"Maruti Suzuki Alto 800 Std (CNG), CNG",
				"Maruti Suzuki Alto 800 Std (CNG), PETROL/CNG",
				"Maruti Suzuki Alto 800 Vxi, PETROL",
				"Maruti Suzuki Alto 800 Vxi, PETROL",
				"Maruti Suzuki Alto K10 LX, PETROL",
				"Maruti Suzuki Alto K10 LXi (Petrol), PETROL",
				"Maruti Suzuki Alto K10 LXi (CNG), CNG",
				"Maruti Suzuki Alto K10 VXi, PETROL",
				"Maruti Suzuki Alto K10 VXi AMT, PETROL",
				"Maruti Suzuki Alto LX (Petrol), PETROL",
				"Maruti Suzuki Alto LX (CNG), CNG",
				"Maruti Suzuki Alto LX (CNG), PETROL/CNG",
				"Maruti Suzuki Alto Lxi (Petrol), PETROL",
				"Maruti Suzuki Alto Lxi (CNG), CNG",
				"Maruti Suzuki Alto Lxi (CNG), PETROL/CNG",
				"Maruti Suzuki Alto Std (Petrol), PETROL",
				"Maruti Suzuki Alto Std (CNG), CNG",
				"Maruti Suzuki Alto Std (CNG), PETROL/CNG",
				"Maruti Suzuki Alto XCITE, PETROL",
				"Maruti Suzuki A-Star Lxi, PETROL",
				"Maruti Suzuki A-Star Vxi, PETROL",
				"Maruti Suzuki A-Star Zxi, PETROL",
				"Maruti Suzuki Baleno Alpha 1.2, PETROL",
				"Maruti Suzuki Baleno Alpha 1.3, DIESEL",
				"Maruti Suzuki Baleno Delta 1.2, PETROL",
				"Maruti Suzuki Baleno Delta 1.3, DIESEL",
				"Maruti Suzuki Baleno LXi, PETROL",
				"Maruti Suzuki Baleno Sigma 1.2, PETROL",
				"Maruti Suzuki Baleno Sigma 1.3, DIESEL",
				"Maruti Suzuki Baleno Std, PETROL",
				"Maruti Suzuki Baleno VXi, PETROL",
				"Maruti Suzuki Baleno Zeta 1.2, PETROL",
				"Maruti Suzuki Baleno Zeta 1.3, DIESEL",
				"Maruti Suzuki Celerio ZXi AMT, PETROL",
				"Maruti Suzuki Celerio ZXi, PETROL",
				"Maruti Suzuki Celerio ZDi, DIESEL",
				"Maruti Suzuki Celerio VXi (CNG), LPG",
				"Maruti Suzuki Celerio VXi (CNG), CNG",
				"Maruti Suzuki Celerio VXi AMT, PETROL",
				"Maruti Suzuki Celerio VXi (Petrol), PETROL",
				"Maruti Suzuki Celerio VDi, DIESEL",
				"Maruti Suzuki Celerio LXi AMT, PETROL",
				"Maruti Suzuki Celerio LXi, PETROL",
				"Maruti Suzuki Celerio LDi, DIESEL",
				"Maruti Suzuki Ciaz VDi, DIESEL",
				"Maruti Suzuki Ciaz VDi +, DIESEL",
				"Maruti Suzuki Ciaz VXi, PETROL",
				"Maruti Suzuki Ciaz VXi+, PETROL",
				"Maruti Suzuki Ciaz ZDi, DIESEL",
				"Maruti Suzuki Ciaz ZDi+, DIESEL",
				"Maruti Suzuki Ciaz ZXi, PETROL",
				"Maruti Suzuki Ciaz ZXI+, PETROL",
				"Maruti Suzuki Eeco 5 Seater (Petrol), PETROL",
				"Maruti Suzuki Eeco 5 Seater (CNG), CNG",
				"Maruti Suzuki Eeco 7 Seater, PETROL",
				"Maruti Suzuki Ertiga LDi, DIESEL",
				"Maruti Suzuki Ertiga LDi, DIESEL",
				"Maruti Suzuki Ertiga LXI (Petrol), PETROL",
				"Maruti Suzuki Ertiga LXI (Petrol), PETROL",
				"Maruti Suzuki Ertiga LXi (CNG), CNG",
				"Maruti Suzuki Ertiga LXi (CNG), PETROL/CNG",
				"Maruti Suzuki Ertiga LXi (CNG), PETROL/CNG",
				"Maruti Suzuki Ertiga VDI 7STR, DIESEL",
				"Maruti Suzuki Ertiga VDI 7STR, DIESEL",
				"Maruti Suzuki Ertiga VXI (Petrol), PETROL",
				"Maruti Suzuki Ertiga VXI (Petrol), PETROL",
				"Maruti Suzuki Ertiga VXI AT (Petrol), PETROL",
				"Maruti Suzuki Ertiga VXI AT (Petrol), PETROL",
				"Maruti Suzuki Ertiga VXI (CNG), CNG",
				"Maruti Suzuki Ertiga VXI (CNG), PETROL/CNG",
				"Maruti Suzuki Ertiga VXI (CNG), PETROL/CNG",
				"Maruti Suzuki Ertiga Zdi 7 Seater, DIESEL",
				"Maruti Suzuki Ertiga Zdi 7 Seater, DIESEL",
				"Maruti Suzuki Ertiga ZXI, PETROL",
				"Maruti Suzuki Ertiga ZXI, PETROL",
				"Maruti Suzuki Esteem AX, PETROL",
				"Maruti Suzuki Esteem D, DIESEL",
				"Maruti Suzuki Esteem Di, DIESEL",
				"Maruti Suzuki Esteem LX, PETROL",
				"Maruti Suzuki Esteem VXi, PETROL",
				"Maruti Suzuki Estilo LX (1061 cc), PETROL",
				"Maruti Suzuki Estilo LX (1061 cc), PETROL",
				"Maruti Suzuki Estilo LX (998 cc), PETROL",
				"Maruti Suzuki Estilo LX (998 cc), PETROL",
				"Maruti Suzuki Estilo Lxi (1061 cc), PETROL",
				"Maruti Suzuki Estilo LXi (998 cc) (Petrol), PETROL",
				"Maruti Suzuki Estilo LXi (998 cc) (Petrol), PETROL",
				"Maruti Suzuki Estilo LXi (998 cc) (CNG), CNG",
				"Maruti Suzuki Estilo LXi (998 cc) (CNG), PETROL/CNG",
				"Maruti Suzuki Estilo Sports, PETROL",
				"Maruti Suzuki Estilo Sports, PETROL",
				"Maruti Suzuki Estilo Vxi (1061 cc), PETROL",
				"Maruti Suzuki Estilo Vxi (1061 cc), PETROL",
				"Maruti Suzuki Estilo Vxi (998 cc), PETROL",
				"Maruti Suzuki Grand Vitara 2.0 AT, PETROL",
				"Maruti Suzuki Grand Vitara 2.0, PETROL",
				"Maruti Suzuki Grand Vitara 2.4 AT, PETROL",
				"Maruti Suzuki Grand Vitara 2.4, PETROL",
				"Maruti Suzuki Grand Vitara XL-7 AT, PETROL",
				"Maruti Suzuki Grand Vitara XL-7 MT, PETROL",
				"Maruti Suzuki Gypsy King HT, PETROL",
				"Maruti Suzuki Gypsy King ST, PETROL",
				"Maruti Suzuki Kizashi CVT, PETROL",
				"Maruti Suzuki Kizashi MT, PETROL",
				"Maruti Suzuki Omni 5 Seater, PETROL",
				"Maruti Suzuki Omni 8 Seater, PETROL",
				"Maruti Suzuki Omni Cargo (Petrol), PETROL",
				"Maruti Suzuki Omni Cargo (Petrol), PETROL",
				"Maruti Suzuki Omni Cargo (LPG), LPG",
				"Maruti Suzuki Omni Cargo (LPG), LPG",
				"Maruti Suzuki Omni E 8 STR BS-IV, PETROL",
				"Maruti Suzuki Omni (LPG), LPG",
				"Maruti Suzuki Omni (LPG), CNG",
				"Maruti Suzuki Omni (LPG), PETROL/LPG",
				"Maruti Suzuki Omni (CNG), LPG",
				"Maruti Suzuki Omni (CNG), CNG",
				"Maruti Suzuki Ritz GENUS VDI, DIESEL",
				"Maruti Suzuki Ritz GENUS VXI, PETROL",
				"Maruti Suzuki Ritz Ldi, DIESEL",
				"Maruti Suzuki Ritz Ldi, DIESEL",
				"Maruti Suzuki Ritz Lxi, PETROL",
				"Maruti Suzuki Ritz Vdi, DIESEL",
				"Maruti Suzuki Ritz Vxi AT, PETROL",
				"Maruti Suzuki Ritz Vxi, PETROL",
				"Maruti Suzuki Ritz Zdi, DIESEL",
				"Maruti Suzuki Ritz Zxi, PETROL",
				"Maruti Suzuki S-Cross Alpha 1.3, DIESEL",
				"Maruti Suzuki S-Cross Alpha 1.6, DIESEL",
				"Maruti Suzuki S-Cross Delta 1.3, DIESEL",
				"Maruti Suzuki S-Cross Delta 1.6, DIESEL",
				"Maruti Suzuki S-Cross Sigma 1.3, DIESEL",
				"Maruti Suzuki S-Cross Zeta 1.3, DIESEL",
				"Maruti Suzuki S-Cross Zeta 1.6, DIESEL",
				"Maruti Suzuki Stingray LXi, PETROL",
				"Maruti Suzuki Stingray VXi, PETROL",
				"Maruti Suzuki Stingray VXi AMT, PETROL",
				"Maruti Suzuki Swift Dzire LDI, DIESEL",
				"Maruti Suzuki Swift Dzire LXi, PETROL",
				"Maruti Suzuki Swift Dzire VDI, DIESEL",
				"Maruti Suzuki Swift Dzire VXi, PETROL",
				"Maruti Suzuki Swift Dzire VXI AMT, PETROL",
				"Maruti Suzuki Swift Dzire ZDI, DIESEL",
				"Maruti Suzuki Swift Dzire ZDI AMT, DIESEL",
				"Maruti Suzuki Swift Dzire ZXI, PETROL",
				"Maruti Suzuki Swift GLAM, PETROL",
				"Maruti Suzuki Swift LDi, DIESEL",
				"Maruti Suzuki Swift LXi, PETROL",
				"Maruti Suzuki Swift VDi, DIESEL",
				"Maruti Suzuki Swift Vxi, PETROL",
				"Maruti Suzuki Swift ZDi, DIESEL",
				"Maruti Suzuki Swift ZXi, PETROL",
				"Maruti Suzuki SX4 VDI, DIESEL",
				"Maruti Suzuki SX4 VXi (Petrol), PETROL",
				"Maruti Suzuki SX4 VXi (CNG), CNG",
				"Maruti Suzuki SX4 VXi (CNG), PETROL/CNG",
				"Maruti Suzuki SX4 ZDI, DIESEL",
				"Maruti Suzuki SX4 ZXi, PETROL",
				"Maruti Suzuki SX4 ZXI AT, PETROL",
				"Maruti Suzuki Versa DX 5 Seater, PETROL",
				"Maruti Suzuki Versa DX 8 Seater, PETROL",
				"Maruti Suzuki Versa DX2 5 Seater, PETROL",
				"Maruti Suzuki Versa DX2 8 Seater, PETROL",
				"Maruti Suzuki Versa STD, PETROL",
				"Maruti Suzuki Wagon R 1.0 LX, PETROL",
				"Maruti Suzuki Wagon R 1.0 LXi (Petrol), PETROL",
				"Maruti Suzuki Wagon R 1.0 LXi (CNG), LPG",
				"Maruti Suzuki Wagon R 1.0 LXi (CNG), CNG",
				"Maruti Suzuki Wagon R 1.0 LXi (LPG), PETROL",
				"Maruti Suzuki Wagon R 1.0 LXi (LPG), LPG",
				"Maruti Suzuki Wagon R 1.0 LXi (LPG), CNG",
				"Maruti Suzuki Wagon R 1.0 LXi (LPG), PETROL/LPG",
				"Maruti Suzuki Wagon R 1.0 VXi, PETROL",
				"Maruti Suzuki Wagon R 1.0 VXi AMT, PETROL",
				"Maruti Suzuki Wagon R AX, PETROL",
				"Maruti Suzuki Wagon R Duo LX, LPG",
				"Maruti Suzuki Wagon R Duo LX, LPG",
				"Maruti Suzuki Wagon R Duo LX, CNG",
				"Maruti Suzuki Wagon R Duo LXi, LPG",
				"Maruti Suzuki Wagon R Duo LXi, CNG",
				"Maruti Suzuki Wagon R LX, PETROL",
				"Maruti Suzuki Wagon R LXi, PETROL",
				"Maruti Suzuki Wagon R VXi, PETROL",
				"Maruti Suzuki Zen D, DIESEL",
				"Maruti Suzuki Zen D PS, DIESEL",
				"Maruti Suzuki Zen D PS, DIESEL",
				"Maruti Suzuki Zen LX, PETROL",
				"Maruti Suzuki Zen LXi, PETROL",
				"Maruti Suzuki Zen VXi, PETROL",
				"Maruti Suzuki Zen VXi, PETROL",
				"Maruti Suzuki Esteem LXi, PETROL",
				"Maruti Suzuki 1000, PETROL",
				"Maruti Suzuki Ciaz Rs ZDI, DIESEL",
				"Maruti Suzuki Ciaz Rs ZXI AT, PETROL",
				"Maruti Suzuki Ciaz Rs ZXI MT, PETROL",
				"Maruti Suzuki Swift Dzire LXI (O), PETROL",
				"Aston Martin DB9, PETROL",
				"Aston Martin DB9 GT, PETROL",
				"Aston Martin DB9 Volante, PETROL",
				"Aston Martin DBS Coupe, PETROL",
				"Aston Martin DBS Volante, PETROL",
				"Aston Martin Rapide S, PETROL",
				"Aston Martin V12 Vantage S, PETROL",
				"Aston Martin V8 Vantage Roadster, PETROL",
				"Aston Martin V8 Vantage Vantage, PETROL",
				"Aston Martin V8 Vantage S, PETROL",
				"Aston Martin Vanquish, PETROL",
				"Aston Martin Virage Virage, PETROL",
				"Aston Martin Virage Volante, PETROL",
				"ICML Extreme LD CRD-Fi 10 Seater, DIESEL",
				"ICML Extreme LD CRD-Fi 9 Seater, DIESEL",
				"ICML Extreme SD CRD-Fi 7 Seater, DIESEL",
				"ICML Extreme SD CRD-Fi 8 Seater, DIESEL",
				"ICML Extreme SD CRD-Fi 9 Seater, DIESEL",
				"ICML Extreme VD CRD-Fi, DIESEL",
				"ICML Extreme VD DI, DIESEL",
				"ICML Rhino Rx DLX, DIESEL",
				"ICML Rhino Rx S1 AC, DIESEL",
				"ICML Rhino Rx S2, DIESEL",
				"Opel Astra 1.6L, PETROL",
				"Opel Corsa GLS, PETROL",
				"Opel Corsa GSI, PETROL",
				"Opel Corsa Sail 1.4, PETROL",
				"Opel Corsa Sail 1.6, PETROL",
				"Opel Vectra Comfort, PETROL",
				"Hummer H2 SUV, PETROL",
				"Hummer H3 Alpha, PETROL",
				"Hummer H3, PETROL",
				"Tata Aria Pleasure 4x2, DIESEL",
				"Tata Aria Pride 4x4, DIESEL",
				"Tata Bolt XE (Diesel), DIESEL",
				"Tata Bolt XE (Petrol), PETROL",
				"Tata Bolt XM (Diesel), DIESEL",
				"Tata Bolt XM (Petrol), PETROL",
				"Tata Bolt XMS (Diesel), DIESEL",
				"Tata Bolt XMS (Petrol), PETROL",
				"Tata Bolt XT (Diesel), DIESEL",
				"Tata Bolt XT (Petrol), PETROL",
				"Tata Indica eV2 GLS eMAX, CNG",
				"Tata Indica eV2 GLX eMAX, CNG",
				"Tata Indica eV2 LS, DIESEL",
				"Tata Indica eV2 LS, DIESEL",
				"Tata Indica eV2 LX, DIESEL",
				"Tata Indica V2 L, DIESEL",
				"Tata Indica V2 LE, DIESEL",
				"Tata Indica V2 LS, DIESEL",
				"Tata Indica V2 LS, DIESEL",
				"Tata Indica V2 LX, PETROL",
				"Tata Indica V2 LX, DIESEL",
				"Tata Indigo eCS GLS (Petrol), PETROL",
				"Tata Indigo eCS GLS (Petrol), PETROL",
				"Tata Indigo eCS GLS eMAX, PETROL",
				"Tata Indigo eCS GLS eMAX, CNG",
				"Tata Indigo eCS GLS eMAX, PETROL/CNG",
				"Tata Indigo eCS GLX, PETROL",
				"Tata Indigo eCS GLX, PETROL",
				"Tata Indigo eCS GLX eMAX, PETROL",
				"Tata Indigo eCS GLX eMAX, CNG",
				"Tata Indigo eCS GLX eMAX, PETROL/CNG",
				"Tata Indigo eCS LS CR4, DIESEL",
				"Tata Indigo eCS LX CR4, DIESEL",
				"Tata Indigo eCS VX CR4, DIESEL",
				"Tata Movus CX, DIESEL",
				"Tata Movus LX, DIESEL",
				"Tata Nano emax CX, CNG",
				"Tata Nano emax LX, CNG",
				"Tata Nano CX, PETROL",
				"Tata Nano GenX XE, PETROL",
				"Tata Nano GenX XM, PETROL",
				"Tata Nano GenX XMA, PETROL",
				"Tata Nano GenX XT, PETROL",
				"Tata Nano GenX XTA, PETROL",
				"Tata Nano LX, PETROL",
				"Tata Nano Twist XE, PETROL",
				"Tata Nano Twist XT, PETROL",
				"Tata Nano XM, CNG",
				"Tata Safari 4x2 EX Dicor, DIESEL",
				"Tata Safari 4x2 GX Dicor, DIESEL",
				"Tata Safari 4x2 LX Dicor, DIESEL",
				"Tata Safari 4x2 VX Dicor, DIESEL",
				"Tata Safari 4x4 EX Dicor, DIESEL",
				"Tata Safari 4x4 GX Dicor, DIESEL",
				"Tata Safari 4x4 VX Dicor, DIESEL",
				"Tata Safari Storme 2.2 EX 4X2, DIESEL",
				"Tata Safari Storme 2.2 LX 4x2, DIESEL",
				"Tata Safari Storme 2.2 VX 4x2, DIESEL",
				"Tata Safari Storme 2.2 VX 4x4, DIESEL",
				"Tata Sumo Gold CX, DIESEL",
				"Tata Sumo Gold EX, DIESEL",
				"Tata Sumo Gold FX, DIESEL",
				"Tata Sumo Gold GX, DIESEL",
				"Tata Sumo Gold LX, DIESEL",
				"Tata Venture CX, DIESEL",
				"Tata Venture EX, DIESEL",
				"Tata Venture GX, DIESEL",
				"Tata Venture LX, DIESEL",
				"Tata Xenon XT EX 4x2, DIESEL",
				"Tata Xenon XT EX 4x4, DIESEL",
				"Tata Zest XE (Diesel), DIESEL",
				"Tata Zest XE (Petrol), PETROL",
				"Tata Zest XM (Diesel), DIESEL",
				"Tata Zest XM (Petrol), PETROL",
				"Tata Zest XMA, DIESEL",
				"Tata Zest XMS (Diesel), DIESEL",
				"Tata Zest XMS (Petrol), PETROL",
				"Tata Zest XT (Diesel), DIESEL",
				"Tata Zest XT (Petrol), PETROL",
				"Tata Zest XTA, DIESEL",
				"Tata Aria Pleasure 4X4, DIESEL",
				"Tata Aria Prestige 4X4, DIESEL",
				"Tata Aria Prestige 4X2, DIESEL",
				"Tata Aria Pure 4x2, DIESEL",
				"Tata Indica LEi, PETROL",
				"Tata Indica LSi, PETROL",
				"Tata Indica LXi, PETROL",
				"Tata Indica eV2 L, DIESEL",
				"Tata Indica eV2 LE, DIESEL",
				"Tata Indica V2 DLS, DIESEL",
				"Tata Indica V2 DLG, DIESEL",
				"Tata Indica V2 DLX, DIESEL",
				"Tata Indica V2 DL, DIESEL",
				"Tata Indica V2 DLE, DIESEL",
				"Tata Indica V2 Xeta GV, PETROL",
				"Tata Indica V2 Xeta GVE, PETROL",
				"Tata Indica V2 Xeta GVG, PETROL",
				"Tata Indica V2 Xeta GVS, PETROL",
				"Tata Indica V2 Xeta GL (1396 cc), PETROL",
				"Tata Indica V2 Xeta GLE (1396 cc), PETROL",
				"Tata Indica V2 Xeta GLS (1396 cc), PETROL",
				"Tata Indica V2 Xeta GL (1193 cc), PETROL",
				"Tata Indica V2 Xeta GLE (Petrol), PETROL",
				"Tata Indica V2 Xeta GLS (1193 cc), PETROL",
				"Tata Indica V2 Xeta GLS 1.2, LPG",
				"Tata Indica V2 Xeta GLS 1.2, CNG",
				"Tata Indica V2 Xeta eGL, PETROL",
				"Tata Indica V2 Xeta GLG (1193 cc), PETROL",
				"Tata Indica V2 Xeta GLG (1396 cc), PETROL",
				"Tata Indica V2 Xeta GLE (LPG), LPG",
				"Tata Indica V2 Xeta GLE (LPG), CNG",
				"Tata Indica V2 Xeta eGLE (Petrol), PETROL",
				"Tata Indica V2 Xeta GLX, PETROL",
				"Tata Indica V2 Xeta eGLS (Petrol), PETROL",
				"Tata Indica V2 Turbo DLS, DIESEL",
				"Tata Indica V2 Turbomax DLE, DIESEL",
				"Tata Indica V2 Turbo DLG, DIESEL",
				"Tata Indica V2 Xeta eGLE(LPG), LPG",
				"Tata Indica V2 Turbomax DLS, DIESEL",
				"Tata Indica V2 DLS Dicor, DIESEL",
				"Tata Indica V2 Xeta eGLX, PETROL",
				"Tata Indica V2 Xeta eGLS(LPG), LPG",
				"Tata Indica V2 Xeta eGLS(LPG), CNG",
				"Tata Indica V2 Turbo DLX, DIESEL",
				"Tata Indica V2 DLG Dicor, DIESEL",
				"Tata Indica Vista Terra Safire, PETROL",
				"Tata Indica Vista Aqua Safire, PETROL",
				"Tata Indica Vista Aura Safire, PETROL",
				"Tata Indica Vista Terra TDI, DIESEL",
				"Tata Indica Vista LE Safire, PETROL",
				"Tata Indica Vista Aqua TDI, DIESEL",
				"Tata Indica Vista Terra Safire-90, PETROL",
				"Tata Indica Vista Aura + Safire, PETROL",
				"Tata Indica Vista Terra Quadrajet, DIESEL",
				"Tata Indica Vista Aura Quadrajet, DIESEL",
				"Tata Indica Vista Aqua Quadrajet, PETROL",
				"Tata Indica Vista Aqua Quadrajet, DIESEL",
				"Tata Indica Vista LE Quadrajet, DIESEL",
				"Tata Indica Vista AURA Safire-90, PETROL",
				"Tata Indigo GLE (1405 cc), PETROL",
				"Tata Indigo GLE (1405 cc), PETROL",
				"Tata Indigo SX, DIESEL",
				"Tata Indigo GSX (1405 cc), PETROL",
				"Tata Indigo GV, PETROL",
				"Tata Indigo GVE, PETROL",
				"Tata Indigo V, DIESEL",
				"Tata Indigo GVS, PETROL",
				"Tata Indigo VE, DIESEL",
				"Tata Indigo LX Dicor, PETROL",
				"Tata Indigo LX Dicor, DIESEL",
				"Tata Indigo VS, DIESEL",
				"Tata Indigo GLS, PETROL",
				"Tata Indigo GLX, PETROL",
				"Tata Indigo GLX, PETROL",
				"Tata Indigo LS TDI, DIESEL",
				"Tata Indigo LS Dicor, DIESEL",
				"Tata Indigo LX TDI, DIESEL",
				"Tata Indigo CS LX TDI, DIESEL",
				"Tata Indigo CS GLE, PETROL",
				"Tata Indigo CS GLS, PETROL",
				"Tata Indigo CS GLX, PETROL",
				"Tata Indigo CS LE TDI, DIESEL",
				"Tata Indigo CS LS Dicor, DIESEL",
				"Tata Indigo CS LS Dicor, DIESEL",
				"Tata Indigo CS LS TDI, DIESEL",
				"Tata Indigo CS LX Dicor, DIESEL",
				"Tata Indigo CS LX Dicor, DIESEL",
				"Tata Indigo eCS LE TDI, DIESEL",
				"Tata Indigo Marina SX, DIESEL",
				"Tata Indigo Marina LS, PETROL",
				"Tata Indigo Marina LS, DIESEL",
				"Tata Indigo Marina LX, DIESEL",
				"Tata Indigo Marina GLE, PETROL",
				"Tata Indigo Marina GLS, PETROL",
				"Tata Indigo Marina GLX, PETROL",
				"Tata Indigo Marina GSX, PETROL",
				"Tata Indigo XL Grand Dicor, DIESEL",
				"Tata Indigo XL Classic, PETROL",
				"Tata Indigo XL Classic Dicor, DIESEL",
				"Tata Indigo XL Grand, PETROL",
				"Tata Tata Manza Aqua Safire, PETROL",
				"Tata Tata Manza Aura Safire, PETROL",
				"Tata Tata Manza Aqua Quadrajet, DIESEL",
				"Tata Tata Manza Aura Quadrajet, DIESEL",
				"Tata Nano Base, PETROL",
				"Tata Safari 4x2 Exi, PETROL",
				"Tata Safari 4x4 Exi, PETROL",
				"Tata Safari 4x2 Vxi, PETROL",
				"Tata Safari 4x4 Vxi, PETROL",
				"Tata Safari 4x2 EX, DIESEL",
				"Tata Safari 4x4 EX, DIESEL",
				"Tata Safari 4x4 LX, DIESEL",
				"Tata Safari 4x2 LX, DIESEL",
				"Tata Safari 4x4 LX Dicor, DIESEL",
				"Tata Sumo Grande GX, DIESEL",
				"Tata Sumo Grande CX, DIESEL",
				"Tata Sumo Grande LX, DIESEL",
				"Tata Sumo Grande EX, DIESEL",
				"Tata Sumo Spacio Gold, DIESEL",
				"Tata Sumo Victa DI GX, DIESEL",
				"Tata Sumo Victa LX, DIESEL",
				"Tata Sumo Victa DI CX, DIESEL",
				"Tata Sumo Victa DI LX, DIESEL",
				"Tata Sumo Victa EX, DIESEL",
				"Tata Sumo Victa DI EX, DIESEL",
				"Tata Sumo Victa GX TC, DIESEL",
				"Tata Indica Vista GLS Safire65, PETROL",
				"Tata Indica Vista GLX Safire65, PETROL",
				"Tata Indica Vista LS TDI, DIESEL",
				"Tata Indica Vista GVX Safire65, PETROL",
				"Tata Indica Vista LX TDI, DIESEL",
				"Tata Indica Vista LS Quadrajet, DIESEL",
				"Tata Indica Vista GLX Safire90, PETROL",
				"Tata Indica Vista LX Quadrajet, DIESEL",
				"Tata Indica Vista VX Quadrajet, DIESEL",
				"Tata Indica Vista GVX Safire90, PETROL",
				"Tata Indica Vista ZX Quadrajet, DIESEL",
				"Tata Indica Vista GZX Safire90, PETROL",
				"Tata Tata Manza Elan Safire, PETROL",
				"Tata Tata Manza Elan Quadrajet, DIESEL",
				"Tata Safari Storme Explorer Edition, DIESEL",
				"Tata Indigo GLE (1396 cc), PETROL",
				"Tata Indigo GSX (1396 cc), PETROL",
				"Tata Indigo GVX, PETROL",
				"Tata Manza EX, DIESEL",
				"Tata Manza GEX, PETROL",
				"Tata Manza GLS, PETROL",
				"Tata Manza GLX, PETROL",
				"Tata Manza GVX, PETROL",
				"Tata Manza LS, DIESEL",
				"Tata Manza LX, DIESEL",
				"Tata Manza VX, DIESEL",
				"Tata Nano Emax XM, CNG",
				"Tata Sierra STD, DIESEL",
				"Tata Sierra Turbo, DIESEL",
				"Tata Sumo Gold CX Turbo, DIESEL",
				"ASHOK LEYLAND Stile LE, DIESEL",
				"ASHOK LEYLAND Stile LS, DIESEL",
				"ASHOK LEYLAND Stile LX, DIESEL",
				"DATSUN GO D, PETROL",
				"DATSUN GO A, PETROL",
				"DATSUN GO T, PETROL",
				"DATSUN GO NXT, PETROL",
				"DATSUN Go Plus D, PETROL",
				"DATSUN Go Plus A, PETROL",
				"DATSUN Go Plus T, PETROL",
				"FORCE MOTORS Gurkha 4X2, DIESEL",
				"FORCE MOTORS Gurkha 4X4, DIESEL",
				"FORCE MOTORS Force One EX, DIESEL",
				"FORCE MOTORS Force One SX, DIESEL",
				"FORCE MOTORS Force One LX, DIESEL",
				"FORCE MOTORS Trax Cruiser 10-Seater, DIESEL",
				"FORCE MOTORS Trax Cruiser 14-Seater, DIESEL",
				"FORCE MOTORS Trax Cruiser 6-Seater, DIESEL",
				"FORCE MOTORS Trax Cruiser Deluxe 10-Seater, DIESEL",
				"FORCE MOTORS Trax Cruiser Deluxe 13-Seater, DIESEL",
				"FORCE MOTORS Trax Gama Classic, DIESEL",
				"FORCE MOTORS Trax Gama DLX, DIESEL",
				"FORCE MOTORS Trax Toofan, DIESEL",
				"RENAULT Kwid STD, PETROL",
				"RENAULT Kwid RXE, PETROL",
				"RENAULT Kwid RXL, PETROL",
				"RENAULT Kwid RXT, PETROL",
				"RENAULT Pulse RxL (Petrol), PETROL",
				"RENAULT Pulse RxL (Diesel), DIESEL",
				"RENAULT Pulse RxZ (Diesel), DIESEL",
				"RENAULT Scala RxL (Petrol), PETROL",
				"RENAULT Scala RxL (Diesel), DIESEL",
				"RENAULT Scala RxZ, DIESEL",
				"RENAULT Lodgy 85 PS STD, DIESEL",
				"RENAULT Lodgy 85 PS RxE, DIESEL",
				"RENAULT Lodgy 85 PS RXL, DIESEL",
				"RENAULT Lodgy 110 PS RxL, DIESEL",
				"RENAULT Lodgy 85 PS RXZ, DIESEL",
				"RENAULT Lodgy 110 PS RXZ, DIESEL",
				"RENAULT Duster RxE, PETROL",
				"RENAULT Duster 85 PS RxE, DIESEL",
				"RENAULT Duster RxL, PETROL",
				"RENAULT Duster 85 PS RxL, DIESEL",
				"RENAULT Duster 110 PS RxL, DIESEL",
				"RENAULT Duster 110 PS RxZ (Option), DIESEL",
				"RENAULT Fluence E2, DIESEL",
				"RENAULT Fluence E4, DIESEL",
				"RENAULT Koleos 4x2 MT, DIESEL",
				"RENAULT Koleos 4x4 MT, DIESEL",
				"RENAULT Koleos 4x4 AT, DIESEL",
				"RENAULT Pulse RxE (Petrol), PETROL",
				"RENAULT Pulse RxZ (Petrol), PETROL",
				"RENAULT Pulse RxE (Diesel), DIESEL",
				"RENAULT Duster 85 PS RxE ADVENTURE, DIESEL",
				"RENAULT Duster 110 PS RxZ, DIESEL",
				"RENAULT Duster 110 PS RxZ Plus, DIESEL",
				"RENAULT Duster 110 PS RxL ADVENTURE, DIESEL",
				"RENAULT Fluence Advantage Edition, DIESEL",
				"RENAULT Fluence 1.5 E2, DIESEL",
				"RENAULT Fluence 2.0 E4, PETROL",
				"RENAULT Fluence 1.5 E4, DIESEL",
				"RENAULT Scala Rxe Diesel, DIESEL",
				"RENAULT Scala Rxe Petrol, PETROL",
				"RENAULT Scala Rxz Petrol AT, PETROL",
				"ROLLS-ROYCE Ghost Series II 6.6, PETROL",
				"ROLLS-ROYCE Ghost Series II EWB, PETROL",
				"ROLLS-ROYCE Wraith Sedan, PETROL",
				"ROLLS-ROYCE Phantom Sedan, PETROL",
				"ROLLS-ROYCE Phantom EWB, PETROL",
				"ROLLS-ROYCE Phantom Coupe 6.8 L, PETROL",
				"ROLLS-ROYCE Drophead Coupe Convertible, PETROL",
				"ROLLS-ROYCE Ghost Extended Wheelbase, PETROL",
				"ROLLS-ROYCE Ghost 6.5, PETROL",
				"Ssangyong Rexton RX5, DIESEL",
				"Ssangyong Rexton RX6, DIESEL",
				"Ssangyong Rexton RX7, DIESEL",
				"ISUZU MU7 High, DIESEL",
				"ISUZU MU7 Base, DIESEL",
				"ISUZU MU7 Premium AT, DIESEL",
				"Ford Figo Base 1.2 Ti-VCT, PETROL",
				"Ford Figo Ambiente 1.2 Ti-VCT, PETROL",
				"Ford Figo Trend 1.2 Ti-VCT, PETROL",
				"Ford Figo Base 1.5 TDCi, DIESEL",
				"Ford Figo Ambiente 1.5 TDCi, DIESEL",
				"Ford Figo Titanium 1.2 Ti-VCT, PETROL",
				"Ford Figo Trend 1.5 TDCi, DIESEL",
				"Ford Figo Titanium Plus 1.2 Ti-VCT, PETROL",
				"Ford Figo Titanium1.5 TDCi, DIESEL",
				"Ford Figo Titanium 1.5 Ti-VCT AT, PETROL",
				"Ford Figo Titanium Plus 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Ambiente 1.2 Ti-VCT, PETROL",
				"Ford Figo Aspire Trend 1.2 Ti-VCT, PETROL",
				"Ford Figo Aspire Ambiente 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Ambiente 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Titanium 1.2 Ti-VCT, PETROL",
				"Ford Figo Aspire Trend 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Trend 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Titanium Plus 1.2 Ti-VCT, PETROL",
				"Ford Figo Aspire Titanium1.5 TDCi, DIESEL",
				"Ford Figo Aspire Titanium1.5 TDCi, DIESEL",
				"Ford Figo Aspire Titanium 1.5 Ti-VCT AT, PETROL",
				"Ford Figo Aspire Titanium Plus 1.5 TDCi, DIESEL",
				"Ford Figo Aspire Titanium Plus 1.5 TDCi, DIESEL",
				"Ford EcoSport Ambiente 1.5L TDCi, DIESEL",
				"Ford EcoSport Trend+ 1.0L EcoBoost, PETROL",
				"Ford EcoSport Trend 1.5L TDCi, DIESEL",
				"Ford EcoSport Trend+ 1.5L TDCi, DIESEL",
				"Ford EcoSport Titanium 1.5L TDCi, DIESEL",
				"Ford EcoSport Titanium+ 1.0L EcoBoost, PETROL",
				"Ford EcoSport Titanium+ 1.5L TDCi, DIESEL",
				"Ford Fiesta Ambiente (Diesel), DIESEL",
				"Ford Fiesta Trend, DIESEL",
				"Ford Fiesta Titanium, DIESEL",
				"Ford Endeavour XLT 4X2, DIESEL",
				"Ford Endeavour XLT 4X4, DIESEL",
				"Ford Endeavour 3.0L Thunder+ 4x4, DIESEL",
				"Ford Endeavour XLT TDCi 4x4, DIESEL",
				"Ford Endeavour XLT TDCi 4x2, DIESEL",
				"Ford Fiesta SXi 1.4 TDCI, DIESEL",
				"Ford Fiesta ZXi 1.6, PETROL",
				"Ford Fiesta ZXi 1.4 TDCi, DIESEL",
				"Ford Fiesta EXI 1.4, PETROL",
				"Ford Fiesta ZXi 1.4, PETROL",
				"Ford Fiesta EXi 1.4 TDCi, DIESEL",
				"Ford Fiesta SXi 1.6, PETROL",
				"Ford Fiesta LE 1.6, PETROL",
				"Ford Fiesta EXi 1.6, PETROL",
				"Ford Fiesta S 1.6, PETROL",
				"Ford Fiesta Classic SXi 1.4 TDCi, DIESEL",
				"Ford Fiesta Classic LXi 1.6, PETROL",
				"Ford Fiesta Classic CLXi 1.6, PETROL",
				"Ford Fiesta Classic LXi 1.4 TDCi, DIESEL",
				"Ford Fiesta Classic CLXi 1.4 TDCi, DIESEL",
				"Ford Fiesta Classic SXi 1.6, PETROL",
				"Ford Figo Duratorq Titanium 1.4, DIESEL",
				"Ford Figo Duratec LXI 1.2, PETROL",
				"Ford Figo Duratec EXI 1.2, PETROL",
				"Ford Figo Duratec ZXI 1.2, PETROL",
				"Ford Figo Duratorq LXI 1.4, DIESEL",
				"Ford Figo Duratec Titanium 1.2, PETROL",
				"Ford Figo Duratorq EXI 1.4, DIESEL",
				"Ford Figo Duratorq ZXI 1.4, DIESEL",
				"Ford Fusion +, PETROL",
				"Ford Fusion 1.6, PETROL",
				"Ford Fusion Plus (Diesel), DIESEL",
				"Ford Fusion Plus (Petrol), PETROL",
				"Ford Fusion 1.4 TDCi, DIESEL",
				"Ford Ikon 1.3 EXi, PETROL",
				"Ford Ikon 1.8 ZXi, PETROL",
				"Ford Ikon 1.3 Flair, PETROL",
				"Ford Ikon 1.6 SXi, PETROL",
				"Ford Ikon Rocam 1.3, PETROL",
				"Ford Ikon DuraTorq 1.4 TDCi, DIESEL",
				"Ford Mondeo Duratec HE, PETROL",
				"Ford Mondeo Ghia Duratec, PETROL",
				"Ford Mondeo Duratorq DI, DIESEL",
				"Ford Figo Celebration Edition (Petrol), PETROL",
				"Ford Figo Celebration Edition (Diesel), DIESEL",
				"Ford Classic 1.4 TDCi Titanium, DIESEL",
				"Ford Classic 1.6 Duratec LXi, PETROL",
				"Ford Classic 1.6 Duratec CLXi, PETROL",
				"Ford Classic 1.4 TDCi LXi, DIESEL",
				"Ford Classic 1.6 Duratec Titanium, PETROL",
				"Ford Classic 1.4 TDCi CLXi, DIESEL",
				"Ford EcoSport Ambiente 1.5 Ti-VCT, PETROL",
				"Ford EcoSport Trend 1.5 Ti-VCT, PETROL",
				"Ford EcoSport Titanium 1.5 Ti-VCT, PETROL",
				"Ford EcoSport Titanium 1.5 Ti-VCT, PETROL",
				"Ford EcoSport Titanium 1.0 Ecoboost, PETROL",
				"Ford EcoSport Titanium 1.5 Ti-VCT AT, PETROL",
				"Ford Fiesta Style MT, PETROL",
				"Ford Fiesta Ambiente (Petrol), PETROL",
				"Ford Fiesta Titanium+, PETROL",
				"Ford Fiesta Style, DIESEL",
				"Ford Endeavour 2.5L 4x2, DIESEL",
				"Ford Endeavour 3.0L 4X4 AT, DIESEL",
				"Ford Endeavour 3.0L 4x2 AT, DIESEL",
				"Ford Endeavour Allterrain edition 4x4 AT, DIESEL",
				"Ford Endeavour Allterrain edition 4x4 AT, DIESEL",
				"Ford Endeavour Hurricane LE, DIESEL",
				"Ford Fiesta Style Petrol AT, PETROL",
				"PREMIER Rio Dx Crdi 1.3, DIESEL",
				"PREMIER Rio Dx Turbo 1.5, DIESEL",
				"PREMIER Rio GLX, PETROL",
				"PREMIER Rio GX, PETROL",
				"PREMIER Rio LX CRDI 1.3, DIESEL",
				"PREMIER Rio LX Turbo 1.5, DIESEL",
				"MASERATI Ghibli (Diesel), DIESEL",
				"MASERATI Quattroporte, DIESEL",
				"MASERATI Quattroporte GTS, PETROL",
				"MASERATI GranTurismo 4.2 V8, PETROL",
				"MASERATI GranCabrio 4.7 V8, PETROL",
				"MASERATI GranTurismo S 4.7, PETROL",
				"MASERATI Quattroporte Sport GT 4.7, PETROL",
				"MASERATI Quattroporte 4.2, PETROL",
				"MASERATI Quattroporte S 4.7, PETROL",
				"MASERATI Grancabrio, PETROL",
				"MASERATI Granturismo, PETROL",
				"MASERATI Granturismo Mc Stardale, PETROL",
				"MASERATI Granturismo Sport, PETROL",
				"MASERATI Quattroporte S, PETROL",
				"MASERATI Quattroporte S Q4, PETROL",
				"Mini Cooper D 3 Door, DIESEL",
				"Mini Cooper S, PETROL",
				"Mini Cooper D 5 Door, DIESEL",
				"Mini Cooper Convertible 1.6, PETROL",
				"Mini Cooper Countryman one, PETROL",
				"Mini Cooper Countryman Cooper D, DIESEL",
				"Mini Cooper Countryman Cooper S, PETROL",
				"Mini Cooper S 1.6, PETROL",
				"DC Avanti Standard, PETROL",
				"Toyota Camry 2.5L AT, PETROL",
				"Toyota Camry Hybrid, PETROL",
				"Toyota Corolla Altis G AT, PETROL",
				"Toyota Corolla Altis G (Petrol), PETROL",
				"Toyota Corolla Altis GL (Petrol), PETROL",
				"Toyota Corolla Altis J, DIESEL",
				"Toyota Corolla Altis J+, DIESEL",
				"Toyota Corolla Altis JS, PETROL",
				"Toyota Corolla Altis LE (Diesel), DIESEL",
				"Toyota Corolla Altis LE (Petrol), PETROL",
				"Toyota Corolla Altis VL AT, PETROL",
				"Toyota Etios Cross 1.2 G, PETROL",
				"Toyota Etios Cross 1.4 GD, DIESEL",
				"Toyota Etios Cross 1.4 VD, DIESEL",
				"Toyota Etios Cross 1.5 V, PETROL",
				"Toyota Etios G, PETROL",
				"Toyota Etios GD, DIESEL",
				"Toyota Etios J PS, PETROL",
				"Toyota Etios J PS, DIESEL",
				"Toyota Etios JD, DIESEL",
				"Toyota Etios Liva G, PETROL",
				"Toyota Etios Liva GD, DIESEL",
				"Toyota Etios Liva J PS, PETROL",
				"Toyota Etios Liva JD, DIESEL",
				"Toyota Etios Liva LE (Diesel), DIESEL",
				"Toyota Etios Liva LE (Petrol), PETROL",
				"Toyota Etios Liva V, PETROL",
				"Toyota Etios Liva VD, DIESEL",
				"Toyota Etios Liva VX, PETROL",
				"Toyota Etios Liva VXD, DIESEL",
				"Toyota Etios V, PETROL",
				"Toyota Etios VD, DIESEL",
				"Toyota Etios VX, PETROL",
				"Toyota Etios VXD, DIESEL",
				"Toyota Etios VXD Xclusive, DIESEL",
				"Toyota Fortuner 2.5 Sportivo 4x2 AT, DIESEL",
				"Toyota Fortuner 2.5 Sportivo 4x2 AT, DIESEL",
				"Toyota Fortuner 2.5 Sportivo 4x2 MT, DIESEL",
				"Toyota Fortuner 2.5 Sportivo 4x2 MT, DIESEL",
				"Toyota Fortuner 3.0 4x2 AT, DIESEL",
				"Toyota Fortuner 3.0 4x2 MT, DIESEL",
				"Toyota Fortuner 3.0 4x4 AT, DIESEL",
				"Toyota Fortuner 3.0 4x4 MT, DIESEL",
				"Toyota Innova 2.5 G 7 Seater, DIESEL",
				"Toyota Innova 2.5 GX 7 Seater, DIESEL",
				"Toyota Innova 2.5 GX 8 Seater, DIESEL",
				"Toyota Innova 2.5 VX 7 Seater, DIESEL",
				"Toyota Innova 2.5 VX 8 Seater, DIESEL",
				"Toyota Innova 2.5 ZX 7 Seater, DIESEL",
				"Toyota Land Cruiser LC 200 VX, DIESEL",
				"Toyota Prius 1.8 Z5, PETROL",
				"Toyota Prius 1.8 Z6, PETROL",
				"Toyota Camry W4 AT, PETROL",
				"Toyota Camry W1 MT, PETROL",
				"Toyota Camry W3 MT, PETROL",
				"Toyota Camry W2 AT, PETROL",
				"Toyota Corolla H4 1.8G, PETROL",
				"Toyota Corolla HE 1.8J, PETROL",
				"Toyota Corolla H1 1.8J, PETROL",
				"Toyota Corolla H2 1.8E, PETROL",
				"Toyota Corolla H3 1.8G, PETROL",
				"Toyota Corolla H5 1.8E, PETROL",
				"Toyota Corolla Altis GL (Diesel), DIESEL",
				"Toyota Corolla Altis 1.8 J, PETROL",
				"Toyota Corolla Altis 1.8 Sport, PETROL",
				"Toyota Corolla Altis 1.8 G, PETROL",
				"Toyota Corolla Altis 1.8 GL, PETROL",
				"Toyota Corolla Altis G (Diesel), DIESEL",
				"Toyota Corolla Altis 1.8 VL AT, PETROL",
				"Toyota Etios J, PETROL",
				"Toyota Etios TRD Sportivo Ltd (Petrol), PETROL",
				"Toyota Etios G SP, PETROL",
				"Toyota Etios TRD Sportivo Ltd (Diesel), DIESEL",
				"Toyota Etios GD SP, DIESEL",
				"Toyota Etios Liva J, PETROL",
				"Toyota Etios Liva G SP, PETROL",
				"Toyota Etios Liva GD SP, DIESEL",
				"Toyota Fortuner 3.0 MT, DIESEL",
				"Toyota Fortuner 3.0 Ltd, DIESEL",
				"Toyota Innova 2.0 G2, PETROL",
				"Toyota Innova 2.0 G3, PETROL",
				"Toyota Innova 2.0 E, PETROL",
				"Toyota Innova 2.5 E, DIESEL",
				"Toyota Innova 2.5 EV MS 8 Seater, DIESEL",
				"Toyota Innova 2.5 EV MS 7 Seater, DIESEL",
				"Toyota Innova 2.0 G4, PETROL",
				"Toyota Innova 2.5 EV PS 8 Seater, DIESEL",
				"Toyota Innova 2.5 EV PS 7 Seater, DIESEL",
				"Toyota Innova 2.5 G4 7 Seater, DIESEL",
				"Toyota Innova 2.0 V, PETROL",
				"Toyota Innova 2.0 V, PETROL",
				"Toyota Innova 2.5 V 7 Seater, DIESEL",
				"Toyota Innova 2.5 V 7 Seater, DIESEL",
				"Toyota Innova 2.5 E 7 Seater, DIESEL",
				"Toyota Innova 2.5 E 8 Seater, DIESEL",
				"Toyota Innova 2.5 EV CS 7 Seater, DIESEL",
				"Toyota Innova 2.0 G1, PETROL",
				"Toyota Innova 2.5 G1, DIESEL",
				"Toyota Innova 2.0 GX 8 Seater, PETROL",
				"Toyota Innova 2.0 GX 8 Seater, DIESEL",
				"Toyota Innova 2.0 VX 8 Seater, PETROL",
				"Toyota Innova Crysta 2.5 VX, DIESEL",
				"Toyota Innova 2.5 E MS 8 Seater, DIESEL",
				"Toyota Innova 2.5 E PS 8 Seater, DIESEL",
				"Toyota Innova Aero Ltd 7 Seater I, DIESEL",
				"Toyota Land Cruiser LC200 VX Standard, DIESEL",
				"Toyota Land Cruiser Prado VX, PETROL",
				"Toyota Qualis FS, DIESEL",
				"Toyota Qualis GS, DIESEL",
				"Toyota Etios Liva VD SP*, DIESEL",
				"Toyota Etios Liva Xclusive (Petrol), PETROL",
				"Toyota Etios Liva V SP*, PETROL",
				"Toyota Etios Liva TRD Sportivo (Petrol), PETROL",
				"Toyota Etios Liva TRD Sportivo (Petrol), PETROL",
				"Toyota Etios Liva Xclusive (Diesel), DIESEL",
				"Toyota Etios Liva TRD Sportivo (Diesel), DIESEL",
				"Toyota Etios VD SP*, DIESEL",
				"Toyota Etios Xclusive (Petrol), PETROL",
				"Toyota Etios V SP*, PETROL",
				"Toyota Etios Xclusive (Diesel), DIESEL",
				"Toyota Innova 2.0 G 8 Seater, PETROL",
				"Toyota Innova 2.0 G 8 Seater, DIESEL",
				"Toyota Corolla Altis Ltd (Petrol), PETROL",
				"Toyota Corolla Altis Aero Ltd (Petrol), PETROL",
				"Toyota Corolla Altis 1.8 J(S), PETROL",
				"Toyota Corolla Altis Aero Ltd (Diesel), DIESEL",
				"Toyota Corolla Altis Ltd (Diesel), DIESEL",
				"Toyota Corolla Altis 1.8 G AT, PETROL",
				"Toyota Corolla Altis G D4 (Diesel), DIESEL",
				"Toyota Corolla Altis Gl D4 (Diesel), DIESEL",
				"Toyota Corolla Altis JS D4 (Diesel), DIESEL",
				"Toyota Corolla Altis VL 1.8L, PETROL",
				"Toyota Fortuner FE, DIESEL",
				"Toyota Prius, PETROL",
				"Toyota Prius Z3 1.8, PETROL",
				"Toyota Prius Z4 1.8, PETROL",
				"GMC Cielo GLE, PETROL",
				"GMC Cielo STD, PETROL",
				"GMC Matiz SA, PETROL",
				"GMC Matiz SD, PETROL",
				"GMC Matiz SE, PETROL",
				"GMC Matiz SG, PETROL",
				"GMC Matiz SP, PETROL",
				"Fiat Punto Evo Active 1.2, PETROL",
				"Fiat Punto Evo Dynamic 1.2, PETROL",
				"Fiat Punto Evo Active Multijet 1.3, DIESEL",
				"Fiat Punto Evo Dynamic Multijet 1.3, DIESEL",
				"Fiat Punto Evo Sportivo 1.3, DIESEL",
				"Fiat Punto Evo Emotion 1.4, PETROL",
				"Fiat Punto Evo Multijet 1.3, DIESEL",
				"Fiat Linea Classic 1.4 L P Classic, PETROL",
				"Fiat Linea Classic 1.3 L Multijet Classic, DIESEL",
				"Fiat Avventura Active 1.4, PETROL",
				"Fiat Avventura Active Multijet 1.3, DIESEL",
				"Fiat Avventura Dynamic 1.4, PETROL",
				"Fiat Avventura Dynamic Multijet 1.3, DIESEL",
				"Fiat Avventura Emotion Multijet 1.3, DIESEL",
				"Fiat Linea Active 1.4, PETROL",
				"Fiat Linea Active 1.3 L Advanced Multijet, DIESEL",
				"Fiat Linea Dynamic 1.3 L Advanced Multijet, DIESEL",
				"Fiat Linea Elegante 1.3 L Advanced Multijet, DIESEL",
				"Fiat Linea Emotion 1.3 L Advanced Multijet, DIESEL",
				"Fiat Abarth Punto T-Jet 1.4 Abarth, PETROL",
				"Fiat Abarth 595 Competizione, PETROL",
				"Fiat 500 Lounge, DIESEL",
				"Fiat 500 Sport, DIESEL",
				"Fiat Adventure Sport 1.6, PETROL",
				"Fiat Linea Emotion 1.3, DIESEL",
				"Fiat Linea Dynamic 1.4, PETROL",
				"Fiat Linea Active 1.3, DIESEL",
				"Fiat Linea Emotion T-Jet, PETROL",
				"Fiat Linea Dynamic 1.3, DIESEL",
				"Fiat Palio D EL 1.9 PS, DIESEL",
				"Fiat Palio D ELX 1.9, DIESEL",
				"Fiat Palio NV 1.2 Sport, PETROL",
				"Fiat Palio NV 1.6 Sport, PETROL",
				"Fiat Palio NV 1.2 EL, PETROL",
				"Fiat Palio NV 1.2 ELX, PETROL",
				"Fiat Palio Stile SDX 1.3, DIESEL",
				"Fiat Palio Stile SL 1.1, PETROL",
				"Fiat Palio Stile SLE 1.1, PETROL",
				"Fiat Palio Stile SLX 1.1, PETROL",
				"Fiat Palio Stile SD 1.3, DIESEL",
				"Fiat Palio Stile Sport 1.6, PETROL",
				"Fiat Palio Stile SDE 1.3, DIESEL",
				"Fiat Punto Active 1.2, PETROL",
				"Fiat Punto Dynamic 1.2, PETROL",
				"Fiat Punto Dynamic 1.4, PETROL",
				"Fiat Punto Emotion 1.2, PETROL",
				"Fiat Punto Active 1.3, DIESEL",
				"Fiat Punto Emotion 1.4, PETROL",
				"Fiat Punto Dynamic 1.3, DIESEL",
				"Fiat Punto Emotion 1.3, DIESEL",
				"Fiat Uno Trend 1.2 AC, PETROL",
				"Fiat Uno ELX 1.2 AC, PETROL",
				"Fiat Uno EL 1.2, PETROL",
				"Fiat Punto Sport, DIESEL",
				"Fiat Linea Emotion 1.4, PETROL",
				"Fiat Linea T-Jet, PETROL",
				"Fiat Linea Active Fire Petrol, PETROL",
				"Fiat Petra EL PS, PETROL",
				"Fiat Petra ELX PS 1.6 L, PETROL",
				"Fiat Punto Evo Emotion 1.3L Multijet Diesel, DIESEL",
				"Volkswagen Polo Trendline 1.2L (Petrol), PETROL",
				"Volkswagen Polo Trendline 1.2L (Petrol), PETROL",
				"Volkswagen Polo Comfortline 1.2L (Petrol), PETROL",
				"Volkswagen Polo Highline1.2L (Petrol), PETROL",
				"Volkswagen Polo Trendline 1.5L (Diesel), DIESEL",
				"Volkswagen Polo Comfortline 1.5L (Diesel), DIESEL",
				"Volkswagen Polo Highline1.5L (Diesel), PETROL",
				"Volkswagen Polo Highline1.5L (Diesel), DIESEL",
				"Volkswagen Polo GT TDI (1498cc), DIESEL",
				"Volkswagen Cross Polo 1.2 MPI, PETROL",
				"Volkswagen Cross Polo 1.5 TDI, DIESEL",
				"Volkswagen Vento Trendline (Petrol), PETROL",
				"Volkswagen Vento Comfortline (Petrol), PETROL",
				"Volkswagen Vento Trendline (Diesel), DIESEL",
				"Volkswagen Vento Highline (Petrol), PETROL",
				"Volkswagen Vento Comfortline AT (Petrol), PETROL",
				"Volkswagen Vento Comfortline (Diesel), DIESEL",
				"Volkswagen Vento Highline (Diesel), DIESEL",
				"Volkswagen Vento Comfortline AT (Diesel), DIESEL",
				"Volkswagen Vento Highline AT (Diesel), DIESEL",
				"Volkswagen Jetta Highline TDI, DIESEL",
				"Volkswagen Beetle 1.4 TSI, PETROL",
				"Volkswagen Jetta Trendline 1.6, PETROL",
				"Volkswagen Polo Highline 1.6L (Petrol), PETROL",
				"Volkswagen Polo Highline1.2L D, DIESEL",
				"Volkswagen Touareg 3.0 V6 TDI, DIESEL",
				"Volkswagen Vento IPL Edition, PETROL",
				"Volkswagen Polo Trendline 1.2L (Diesel), DIESEL",
				"Volkswagen Polo Trendline 1.2L (Diesel), DIESEL",
				"Volkswagen Polo SR 1.2L (Petrol), PETROL",
				"Volkswagen Polo Comfortline 1.2L (Diesel), DIESEL",
				"Volkswagen Polo GT TSI, PETROL",
				"Volkswagen Polo GT TDI (1598cc), DIESEL",
				"Volkswagen Vento Style (Petrol), PETROL",
				"Volkswagen Vento Style (Diesel), DIESEL",
				"Volkswagen Vento Highline AT (Petrol), PETROL",
				"Volkswagen Vento TSI, PETROL",
				"Volkswagen Beetle 2.0 AT, PETROL",
				"Volkswagen Passat Highline DSG, DIESEL",
				"Volkswagen Passat 2.0 PD DSG, DIESEL",
				"Volkswagen Passat 1.8L TSI, PETROL",
				"Volkswagen Passat Trendline MT, DIESEL",
				"Volkswagen Passat Comfortline DSG, DIESEL",
				"Volkswagen Phaeton 3.6L, PETROL",
				"Volkswagen Jetta Comfortline Petrol, PETROL",
				"Volkswagen Jetta Comfortline 1.9 TDI AT, DIESEL",
				"Volkswagen Jetta Comfortline 2.0L TDI, DIESEL",
				"Volkswagen Jetta Trendline 1.9 TDI, DIESEL",
				"Volkswagen Jetta Trendline 2.0L TDI, DIESEL",
				"Volkswagen Vento Highline 12.L Petrol, PETROL",
				"Mitsubishi Pajero Sport 2.5 AT, DIESEL",
				"Mitsubishi Pajero Sport 2.5 MT, DIESEL",
				"Mitsubishi Cedia Spirit ALPG, LPG",
				"Mitsubishi Cedia Sports, PETROL",
				"Mitsubishi Cedia Spirit, PETROL",
				"Mitsubishi Cedia Elegance, PETROL",
				"Mitsubishi Cedia Select, PETROL",
				"Mitsubishi Cedia Select ALPG, LPG",
				"Mitsubishi Challenger 2.8, DIESEL",
				"Mitsubishi Lancer LXd 2.0, DIESEL",
				"Mitsubishi Lancer LXi 1.5, PETROL",
				"Mitsubishi Montero 3.2 DI-D AT, DIESEL",
				"Mitsubishi Montero 3.2 GLS, DIESEL",
				"Mitsubishi Montero 3.2 DI-D MT, DIESEL",
				"Mitsubishi Pajero GLX 2.8 CRZ, DIESEL",
				"Mitsubishi Pajero SFX 2.8, DIESEL",
				"Mitsubishi Outlander 2.4 MIVEC, PETROL",
				"Mitsubishi Outlander 2.4 Chrome Ltd, PETROL",
				"Mitsubishi Lancer Evolution X, PETROL",
				"Mitsubishi Pajero Sport 2.8L, DIESEL");
	return arrCarList.map( function (car) {
		return {
			value: car.toLowerCase(),
			display: car
		};
	});
	}
	//filter function for search query
	function createFilterFor(query) {
		var lowercaseQuery = angular.lowercase(query);
		return function filterFn(car) {
			return (car.value.indexOf(lowercaseQuery) === 0);
		};
	}
} 

app.controller('ChatTitleCtrl', ['$scope', function ($scope) {
	$scope.maximChatbox = function () {
		var e = document.getElementById("minim-chat");
		e.style.display = "block";
		var e = document.getElementById("maxi-chat");
		e.style.display = "none";
		var e = document.getElementById("chatbox");
		e.style.margin = "0";
		var e = document.getElementById("animHelpText");
		e.style.display = "none";
	};
	$scope.minimChatbox = function () {
		var e = document.getElementById("minim-chat");
		e.style.display = "none";
		var e = document.getElementById("maxi-chat");
		e.style.display = "block";
		var e = document.getElementById("chatbox");
		e.style.margin = "0 0 -53vh 0";
		var e = document.getElementById("animHelpText");
		e.style.display = "block";
	};
}]);

function escapify(str){
	var temp = str.replace("'", "\'");
	var temp2 = temp.replace('"', '\"');
	return temp2;
}